module.exports = {
  这个: 'zhè ge',
  成为: 'chéng wéi',
  认为: 'rèn wéi',
  作为: 'zuò wéi',
  部分: 'bù fen',
  要求: 'yāo qiú',
  应该: 'yīng gāi',
  增长: 'zēng zhǎng',
  提供: 'tí gōng',
  觉得: 'jué de',
  任务: 'rèn wu',
  那个: 'nà ge',
  称为: 'chēng wéi',
  为主: 'wéi zhǔ',
  了解: 'liǎo jiě',
  处理: 'chǔ lǐ',
  皇上: 'huáng shang',
  只要: 'zhǐ yào',
  大量: 'dà liàng',
  力量: 'lì liàng',
  几乎: 'jī hū',
  干部: 'gàn bù',
  目的: 'mù dì',
  行为: 'xíng wéi',
  只见: 'zhǐ jiàn',
  认识: 'rèn shi',
  市长: 'shì zhǎng',
  师父: 'shī fu',
  调查: 'diào chá',
  重新: 'chóng xīn',
  分为: 'fēn wéi',
  知识: 'zhī shi',
  导弹: 'dǎo dàn',
  行业: 'háng yè',
  质量: 'zhì liàng',
  银行: 'yín háng',
  参与: 'cān yù',
  充分: 'chōng fèn',
  尽管: 'jǐn guǎn',
  生长: 'shēng zhǎng',
  数量: 'shù liàng',
  应当: 'yīng dāng',
  院长: 'yuàn zhǎng',
  强调: 'qiáng diào',
  只能: 'zhǐ néng',
  音乐: 'yīn yuè',
  以为: 'yǐ wéi',
  处于: 'chǔ yú',
  晚上: 'wǎn shang',
  部长: 'bù zhǎng',
  蒙古: 'měng gǔ',
  只有: 'zhǐ yǒu',
  适当: 'shì dàng',
  只好: 'zhǐ hǎo',
  成长: 'chéng zhǎng',
  高兴: 'gāo xìng',
  不了: 'bù liǎo',
  产量: 'chǎn liàng',
  胖子: 'pàng zi',
  显得: 'xiǎn de',
  只是: 'zhǐ shì',
  似的: 'shì de',
  率领: 'shuài lǐng',
  改为: 'gǎi wéi',
  不禁: 'bù jīn',
  成分: 'chéng fèn',
  答应: 'dā yìng',
  少年: 'shào nián',
  兴趣: 'xìng qù',
  太监: 'tài jian',
  休息: 'xiū xi',
  校长: 'xiào zhǎng',
  更新: 'gēng xīn',
  合同: 'hé tong',
  喝道: 'hè dào',
  重庆: 'chóng qìng',
  重建: 'chóng jiàn',
  使得: 'shǐ de',
  审查: 'shěn chá',
  累计: 'lěi jì',
  给予: 'jǐ yǔ',
  上去: 'shǎng qù',
  行情: 'háng qíng',
  极为: 'jí wéi',
  冠军: 'guàn jūn',
  仿佛: 'fǎng fú',
  头发: 'tóu fa',
  投降: 'tóu xiáng',
  家长: 'jiā zhǎng',
  仔细: 'zǐ xì',
  要是: 'yào shi',
  将领: 'jiàng lǐng',
  含量: 'hán liàng',
  更为: 'gèng wéi',
  积累: 'jī lěi',
  地处: 'dì chǔ',
  县长: 'xiàn zhǎng',
  少女: 'shào nǚ',
  路上: 'lù shang',
  只怕: 'zhǐ pà',
  能量: 'néng liàng',
  储量: 'chǔ liàng',
  供应: 'gōng yìng',
  挑战: 'tiǎo zhàn',
  西藏: 'xī zàng',
  记得: 'jì de',
  影片: 'yǐng piān',
  总量: 'zǒng liàng',
  当真: 'dàng zhēn',
  将士: 'jiàng shì',
  差别: 'chā bié',
  较为: 'jiào wéi',
  照片: 'zhào piān',
  长老: 'zhǎng lǎo',
  大夫: 'dài fu',
  差异: 'chā yì',
  懂得: 'dǒng de',
  尽量: 'jǐn liàng',
  模样: 'mú yàng',
  的确: 'dí què',
  为首: 'wéi shǒu',
  便宜: 'pián yi',
  更名: 'gēng míng',
  石头: 'shí tou',
  州长: 'zhōu zhǎng',
  为止: 'wéi zhǐ',
  漂亮: 'piào liang',
  炮弹: 'pào dàn',
  藏族: 'zàng zú',
  角色: 'jué sè',
  当作: 'dàng zuò',
  尽快: 'jǐn kuài',
  人为: 'rén wéi',
  重复: 'chóng fù',
  胡同: 'hú tòng',
  差距: 'chā jù',
  弟兄: 'dì xiong',
  大将: 'dà jiàng',
  睡觉: 'shuì jiào',
  一觉: 'yí jiào',
  团长: 'tuán zhǎng',
  队长: 'duì zhǎng',
  区长: 'qū zhǎng',
  难得: 'nán dé',
  丫头: 'yā tou',
  打听: 'dǎ ting',
  会长: 'huì zhǎng',
  弟弟: 'dì di',
  王爷: 'wáng ye',
  当天: 'dàng tiān',
  重量: 'zhòng liàng',
  誉为: 'yù wéi',
  家伙: 'jiā huo',
  华山: 'huà shān',
  椅子: 'yǐ zi',
  流量: 'liú liàng',
  长大: 'zhǎng dà',
  勉强: 'miǎn qiǎng',
  会计: 'kuài jì',
  分散: 'fēn sǎn',
  过分: 'guò fèn',
  济南: 'jǐ nán',
  调动: 'diào dòng',
  燕京: 'yān jīng',
  少将: 'shào jiàng',
  中毒: 'zhòng dú',
  晓得: 'xiǎo dé',
  变更: 'biàn gēng',
  认得: 'rèn de',
  苹果: 'píng guǒ',
  念头: 'niàn tou',
  挣扎: 'zhēng zhá',
  三藏: 'sān zàng',
  剥削: 'bō xuē',
  丞相: 'chéng xiàng',
  少量: 'shǎo liàng',
  寻思: 'xún si ',
  夺得: 'duó dé',
  干线: 'gàn xiàn',
  呼吁: 'hū yù',
  戏曲: 'xì qǔ',
  处罚: 'chǔ fá',
  长官: 'zhǎng guān',
  见长: 'jiàn zhǎng',
  柏林: 'bó lín',
  亲戚: 'qīn qi',
  身分: 'shēn fèn',
  胳膊: 'gē bo',
  着手: 'zhuó shǒu',
  炸弹: 'zhà dàn',
  咳嗽: 'ké sou',
  西边: 'xī bian',
  赢得: 'yíng de',
  叶子: 'yè zi',
  外长: 'wài zhǎng',
  供给: 'gōng jǐ',
  师长: 'shī zhǎng',
  变量: 'biàn liàng',
  应有: 'yīng yǒu',
  下载: 'xià zài',
  乐器: 'yuè qì',
  间接: 'jiàn jiē',
  底下: 'dǐ xia',
  打扮: 'dǎ ban',
  子弹: 'zǐ dàn',
  弹药: 'dàn yào',
  热量: 'rè liàng',
  削弱: 'xuē ruò',
  骨干: 'gǔ gàn',
  容量: 'róng liàng',
  模糊: 'mó hu',
  转动: 'zhuàn dòng',
  落下: 'là xià',
  称呼: 'chēng hu',
  科长: 'kē zhǎng',
  处置: 'chǔ zhì',
  歌曲: 'gē qǔ',
  着重: 'zhuó zhòng',
  着急: 'zháo jí',
  强迫: 'qiǎng pò',
  庭长: 'tíng zhǎng',
  首相: 'shǒu xiàng',
  喇嘛: 'lǎ ma',
  镇长: 'zhèn zhǎng',
  只管: 'zhǐ guǎn',
  重重: 'chóng chóng',
  免得: 'miǎn de',
  灾难: 'zāi nàn',
  着实: 'zhuó shí',
  所得: 'suǒ de',
  度假: 'dù jià',
  真相: 'zhēn xiàng',
  相貌: 'xiàng mào',
  处分: 'chǔ fèn',
  委屈: 'wěi qu',
  为期: 'wéi qī',
  伯伯: 'bó bo',
  圈子: 'quān zi',
  见识: 'jiàn shi',
  笼罩: 'lǒng zhào',
  外边: 'wài bian',
  与会: 'yù huì',
  都督: 'dū du',
  成都: 'chéng dū',
  六安: 'lù ān',
  都城: 'dū chéng',
  宰相: 'zǎi xiàng',
  较量: 'jiào liàng',
  对称: 'duì chèn',
  总长: 'zǒng zhǎng',
  相公: 'xiàng gong',
  空白: 'kòng bái',
  大王: 'dài wáng',
  打量: 'dǎ liang',
  水分: 'shuǐ fèn',
  舌头: 'shé tou',
  没收: 'mò shōu',
  行李: 'xíng li',
  判处: 'pàn chǔ',
  散文: 'sǎn wén',
  处境: 'chǔ jìng',
  孙子: 'sūn zi',
  拳头: 'quán tou',
  打发: 'dǎ fa',
  组长: 'zǔ zhǎng',
  骨头: 'gú tou',
  宁可: 'nìng kě',
  更换: 'gēng huàn',
  薄弱: 'bó ruò',
  还原: 'huán yuán',
  重修: 'chóng xiū',
  重来: 'chóng lái',
  东边: 'dōng bian',
  同行: 'tóng háng',
  只顾: 'zhǐ gù',
  爱好: 'ài hào',
  馒头: 'mán tou',
  军长: 'jūn zhǎng',
  散发: 'sàn fà',
  首长: 'shǒu zhǎng',
  厂长: 'chǎng zhǎng',
  司长: 'sī zhǎng',
  长子: 'zhǎng zǐ',
  强劲: 'qiáng jìng',
  恰当: 'qià dàng',
  头儿: 'tou er',
  站长: 'zhàn zhǎng',
  折腾: 'zhē teng',
  相处: 'xiāng chǔ',
  统率: 'tǒng shuài',
  中将: 'zhōng jiàng',
  命中: 'mìng zhòng',
  名将: 'míng jiàng',
  左边: 'zuǒ bian',
  木头: 'mù tou',
  动弹: 'dòng tan',
  地壳: 'dì qiào',
  干活: 'gàn huó',
  少爷: 'shào ye',
  难民: 'nàn mín',
  水量: 'shuǐ liàng',
  补给: 'bǔ jǐ',
  尾巴: 'wěi ba',
  来得: 'lái de',
  好奇: 'hào qí',
  钥匙: 'yào shi',
  当做: 'dàng zuò',
  沉着: 'chén zhuó',
  哑巴: 'yǎ ba',
  车子: 'chē zi',
  上将: 'shàng jiàng',
  恶心: 'ě xin',
  担子: 'dàn zi',
  应届: 'yīng jiè',
  行列: 'háng liè',
  主角: 'zhǔ jué',
  运转: 'yùn zhuàn',
  兄长: 'xiōng zhǎng',
  格式: 'gé shi',
  正月: 'zhēng yuè',
  营长: 'yíng zhǎng',
  当成: 'dàng chéng',
  右边: 'yòu bian',
  女婿: 'nǚ xu',
  咽喉: 'yān hóu',
  当晚: 'dàng wǎn',
  重阳: 'chóng yáng',
  化为: 'huà wéi',
  吐蕃: 'tǔ bō',
  钻进: 'zuān jìn',
  乐队: 'yuè duì',
  亮相: 'liàng xiàng',
  被子: 'bèi zi',
  舍得: 'shě de',
  杉木: 'shā mù',
  击中: 'jī zhòng',
  里边: 'lǐ bian',
  排长: 'pái zhǎng',
  假期: 'jià qī',
  分量: 'fèn liàng',
  数次: 'shuò cì',
  提防: 'dī fáng',
  吆喝: 'yāo he',
  查处: 'chá chǔ',
  量子: 'liàng zǐ',
  里头: 'lǐ tou',
  调研: 'diào yán',
  伺候: 'cì hou',
  重申: 'chóng shēn',
  枕头: 'zhěn tou',
  拚命: 'pàn mìng',
  社长: 'shè zhǎng',
  苦难: 'kǔ nàn',
  归还: 'guī huán',
  危难: 'wēi nàn',
  批量: 'pī liàng',
  畜牧: 'xù mù',
  点着: 'diǎn zháo',
  甚为: 'shèn wéi',
  小将: 'xiǎo jiàng',
  着眼: 'zhuó yǎn',
  处死: 'chǔ sǐ',
  厌恶: 'yàn wù',
  鼓乐: 'gǔ yuè',
  树干: 'shù gàn',
  秘鲁: 'bì lǔ',
  大方: 'dà fang',
  外头: 'wài tou',
  班长: 'bān zhǎng',
  星宿: 'xīng xiù',
  宁愿: 'nìng yuàn',
  钦差: 'qīn chāi',
  为数: 'wéi shù',
  勾当: 'gòu dàng',
  削减: 'xuē jiǎn',
  间谍: 'jiàn dié',
  埋怨: 'mán yuàn',
  结实: 'jiē shi',
  计量: 'jì liàng',
  淹没: 'yān mò',
  村长: 'cūn zhǎng',
  连长: 'lián zhǎng',
  自给: 'zì jǐ',
  下边: 'xià bian',
  武将: 'wǔ jiàng',
  温差: 'wēn chā',
  直奔: 'zhí bèn',
  供求: 'gōng qiú',
  剂量: 'jì liàng',
  道长: 'dào zhǎng',
  泄露: 'xiè lòu',
  王八: 'wáng ba',
  切割: 'qiē gē',
  间隔: 'jiàn gé',
  一晃: 'yì huǎng',
  长假: 'cháng jià',
  令狐: 'líng hú',
  为害: 'wéi hài',
  句子: 'jù zi',
  偿还: 'cháng huán',
  疙瘩: 'gē dā',
  燕山: 'yān shān',
  堵塞: 'dǔ sè',
  夺冠: 'duó guàn',
  扎实: 'zhā shi',
  电荷: 'diàn hè',
  看守: 'kān shǒu',
  复辟: 'fù bì',
  郁闷: 'yù mèn',
  尽早: 'jǐn zǎo',
  切断: 'qiē duàn',
  指头: 'zhǐ tou',
  为生: 'wéi shēng',
  畜生: 'chù sheng',
  切除: 'qiē chú',
  着力: 'zhuó lì',
  着想: 'zhuó xiǎng',
  级差: 'jí chā',
  投奔: 'tóu bèn',
  棍子: 'gùn zi',
  含糊: 'hán hu',
  少妇: 'shào fù',
  兴致: 'xìng zhì',
  纳闷: 'nà mèn',
  干流: 'gàn liú',
  卷起: 'juǎn qǐ',
  扇子: 'shàn zi',
  更改: 'gēng gǎi',
  笼络: 'lǒng luò',
  喇叭: 'lǎ ba',
  载荷: 'zài hè',
  妥当: 'tuǒ dàng',
  为难: 'wéi nán',
  着陆: 'zhuó lù',
  燕子: 'yàn zi',
  干吗: 'gàn má',
  白发: 'bái fà',
  总得: 'zǒng děi',
  夹击: 'jiā jī',
  曝光: 'bào guāng',
  曲调: 'qǔ diào',
  相机: 'xiàng jī',
  叫化: 'jiào huā',
  角逐: 'jué zhú',
  啊哟: 'ā yō',
  载重: 'zài zhòng',
  长辈: 'zhǎng bèi',
  出差: 'chū chāi',
  垛口: 'duǒ kǒu',
  撇开: 'piē kāi',
  厅长: 'tīng zhǎng',
  组分: 'zǔ fèn',
  误差: 'wù chā',
  家当: 'jiā dàng',
  传记: 'zhuàn jì',
  个子: 'gè zi',
  铺设: 'pū shè',
  干事: 'gàn shì',
  杆菌: 'gǎn jūn',
  五更: 'wǔ gēng',
  定量: 'dìng liàng',
  运载: 'yùn zài',
  会儿: 'huì er',
  酋长: 'qiú zhǎng',
  重返: 'chóng fǎn',
  差额: 'chā é',
  露面: 'lòu miàn',
  钻研: 'zuān yán',
  大城: 'dài chéng',
  上当: 'shàng dàng',
  销量: 'xiāo liàng',
  洋行: 'yáng háng',
  作坊: 'zuō fang',
  照相: 'zhào xiàng',
  哎呀: 'āi yā',
  调集: 'diào jí',
  看中: 'kàn zhòng',
  议长: 'yì zhǎng',
  风筝: 'fēng zheng',
  辟邪: 'bì xié',
  空隙: 'kòng xì',
  更迭: 'gēng dié',
  偏差: 'piān chā',
  声调: 'shēng diào',
  农行: 'nóng háng',
  适量: 'shì liàng',
  屯子: 'tún zi',
  无量: 'wú liàng',
  空地: 'kòng dì',
  调度: 'diào dù',
  一曲: 'yì qǔ',
  散射: 'sǎn shè',
  太行: 'tài háng',
  创伤: 'chuāng shāng',
  海参: 'hǎi shēn',
  满载: 'mǎn zài',
  重叠: 'chóng dié',
  落差: 'luò chā',
  单调: 'dān diào',
  老将: 'lǎo jiàng',
  人参: 'rén shēn',
  间断: 'jiàn duàn',
  重现: 'chóng xiàn',
  夹杂: 'jiā zá',
  调用: 'diào yòng',
  萝卜: 'luó bo',
  附着: 'fù zhuó',
  应声: 'yīng shēng',
  主将: 'zhǔ jiàng',
  罪过: 'zuì guo',
  咀嚼: 'jǔ jué',
  为政: 'wéi zhèng',
  过量: 'guò liàng',
  乐曲: 'yuè qǔ',
  负荷: 'fù hè',
  枪弹: 'qiāng dàn',
  悄然: 'qiǎo rán',
  处方: 'chǔ fāng',
  悄声: 'qiǎo shēng',
  曲子: 'qǔ zi',
  情调: 'qíng diào',
  挑衅: 'tiǎo xìn',
  代为: 'dài wéi',
  了结: 'liǎo jié',
  打中: 'dǎ zhòng',
  酒吧: 'jiǔ bā',
  作曲: 'zuò qǔ',
  懒得: 'lǎn de',
  增量: 'zēng liàng',
  衣着: 'yī zhuó',
  部将: 'bù jiàng',
  要塞: 'yào sài',
  茶几: 'chá jī',
  杠杆: 'gàng gǎn',
  出没: 'chū mò',
  鲜有: 'xiǎn yǒu',
  间隙: 'jiàn xì',
  重担: 'zhòng dàn',
  重演: 'chóng yǎn',
  重试: 'chóng shì',
  应酬: 'yìng chou',
  只当: 'zhǐ dāng',
  毋宁: 'wú nìng',
  包扎: 'bāo zā',
  前头: 'qián tou',
  卷烟: 'juǎn yān',
  非得: 'fēi děi',
  弹道: 'dàn dào',
  杆子: 'gān zi',
  门将: 'mén jiàng',
  后头: 'hòu tou',
  标识: 'biāo zhì',
  喝彩: 'hè cǎi',
  暖和: 'nuǎn huo',
  更深: 'gēng shēn',
  累积: 'lěi jī',
  引得: 'yǐn de',
  调遣: 'diào qiǎn',
  倔强: 'jué jiàng',
  宝藏: 'bǎo zàng',
  丧事: 'sāng shì',
  约莫: 'yuē mo',
  纤夫: 'qiàn fū',
  更替: 'gēng tì',
  装载: 'zhuāng zài',
  背包: 'bēi bāo',
  帖子: 'tiě zi',
  松散: 'sōng sǎn',
  支行: 'zhī háng',
  呼喝: 'hū hè',
  可恶: 'kě wù',
  自转: 'zì zhuàn',
  供电: 'gōng diàn',
  反省: 'fǎn xǐng',
  坦率: 'tǎn shuài',
  苏打: 'sū dá',
  本分: 'běn fèn',
  落得: 'luò de',
  鄙薄: 'bǐ bó',
  相间: 'xiāng jiàn',
  单薄: 'dān bó',
  混蛋: 'hún dàn',
  发难: 'fā nàn',
  贞观: 'zhēn guàn',
  附和: 'fù hè',
  能耐: 'néng nai',
  吓唬: 'xià hu',
  未了: 'wèi liǎo',
  引着: 'yǐn zháo',
  抽调: 'chōu diào',
  沙子: 'shā zi',
  席卷: 'xí juǎn',
  标的: 'biāo dì',
  别扭: 'biè niu',
  思量: 'sī liang',
  喝采: 'hè cǎi',
  论语: 'lún yǔ',
  盖子: 'gài zi',
  曲艺: 'qǔ yì',
  分外: 'fèn wài',
  弄堂: 'lòng táng',
  乐舞: 'yuè wǔ',
  雨量: 'yǔ liàng',
  毛发: 'máo fà',
  差遣: 'chāi qiǎn',
  曲目: 'qǔ mù',
  背负: 'bēi fù',
  转速: 'zhuàn sù',
  声乐: 'shēng yuè',
  夹攻: 'jiā gōng',
  供水: 'gōng shuǐ',
  主干: 'zhǔ gàn',
  逃难: 'táo nàn',
  惩处: 'chéng chǔ',
  长相: 'zhǎng xiàng',
  公差: 'gōng chāi',
  行当: 'háng dang',
  榴弹: 'liú dàn',
  省得: 'shěng de',
  条子: 'tiáo zi',
  重围: 'chóng wéi',
  阻塞: 'zǔ sè',
  劲风: 'jìng fēng',
  纠葛: 'jiū gé',
  颠簸: 'diān bǒ',
  点中: 'diǎn zhòng',
  避难: 'bì nàn',
  重创: 'zhòng chuāng',
  姥姥: 'lǎo lao',
  迷糊: 'mí hu',
  公家: 'gōng jia',
  几率: 'jī lǜ',
  苦闷: 'kǔ mèn',
  度量: 'dù liàng',
  差错: 'chā cuò',
  暑假: 'shǔ jià',
  参差: 'cēn cī',
  搭载: 'dā zài',
  助长: 'zhù zhǎng',
  相称: 'xiāng chèn',
  红晕: 'hóng yùn',
  舍命: 'shě mìng',
  喜好: 'xǐ hào',
  列传: 'liè zhuàn',
  劲敌: 'jìng dí',
  蛤蟆: 'há má',
  请假: 'qǐng jià',
  钉子: 'dīng zi',
  沉没: 'chén mò',
  高丽: 'gāo lí',
  休假: 'xiū jià',
  无为: 'wú wéi',
  巴结: 'bā jie',
  了得: 'liǎo dé',
  变相: 'biàn xiàng',
  核弹: 'hé dàn',
  亲家: 'qìng jia',
  承载: 'chéng zài',
  行家: 'háng jia',
  喝问: 'hè wèn',
  还击: 'huán jī',
  交还: 'jiāo huán',
  将令: 'jiàng lìng',
  单于: 'chán yú',
  空缺: 'kòng quē',
  绿林: 'lù lín',
  胆量: 'dǎn liàng',
  执着: 'zhí zhuó',
  低调: 'dī diào',
  责难: 'zé nàn',
  闭塞: 'bì sè',
  轻薄: 'qīng bó',
  得当: 'dé dàng',
  占卜: 'zhān bǔ',
  排行: 'pái háng',
  扫帚: 'sào zhou',
  龟兹: 'qiū cí',
  年长: 'nián zhǎng',
  外传: 'wài zhuàn',
  头子: 'tóu zi',
  裁缝: 'cái féng',
  礼乐: 'lǐ yuè',
  血泊: 'xuè pō',
  散乱: 'sǎn luàn',
  动量: 'dòng liàng',
  倒腾: 'dǎo teng',
  取舍: 'qǔ shě',
  咱家: 'zá jiā',
  长发: 'cháng fà',
  爪哇: 'zhǎo wā',
  弹壳: 'dàn ké',
  省悟: 'xǐng wù',
  嚷嚷: 'rāng rang',
  连累: 'lián lěi',
  应得: 'yīng dé',
  族长: 'zú zhǎng',
  患难: 'huàn nàn',
  柜子: 'guì zi',
  擂鼓: 'léi gǔ',
  眩晕: 'xuàn yùn',
  调配: 'diào pèi',
  躯干: 'qū gàn',
  差役: 'chāi yì',
  坎坷: 'kǎn kě',
  少儿: 'shào ér',
  乐团: 'yuè tuán',
  养分: 'yǎng fèn',
  退还: 'tuì huán',
  格调: 'gé diào',
  语调: 'yǔ diào',
  音调: 'yīn diào',
  乐府: 'yuè fǔ',
  古朴: 'gǔ piáo',
  打点: 'dǎ dian',
  差使: 'chāi shǐ',
  磨难: 'mó nàn',
  匀称: 'yún chèn',
  瘦削: 'shòu xuē',
  膏药: 'gāo yao',
  吞没: 'tūn mò',
  调任: 'diào rèn',
  散居: 'sǎn jū',
  上头: 'shàng tóu',
  大难: 'dà nàn',
  风靡: 'fēng mǐ',
  放假: 'fàng jià',
  估量: 'gū liang',
  失当: 'shī dàng',
  中弹: 'zhòng dàn',
  妄为: 'wàng wéi',
  长者: 'zhǎng zhě',
  起哄: 'qǐ hòng',
  末了: 'mò liǎo',
  相声: 'xiàng sheng',
  校正: 'jiào zhèng',
  劝降: 'quàn xiáng',
  矢量: 'shǐ liàng',
  沉闷: 'chén mèn',
  给与: 'jǐ yǔ',
  解法: 'xiè fǎ',
  塞外: 'sài wài',
  将校: 'jiàng xiào',
  嗜好: 'shì hào',
  没落: 'mò luò',
  朴刀: 'pō dāo',
  片子: 'piān zi',
  切削: 'qiē xiāo',
  弹丸: 'dàn wán',
  昆曲: 'kūn qǔ',
  雅致: 'yǎ zhi',
  稀薄: 'xī bó',
  亏得: 'kuī de',
  死难: 'sǐ nàn',
  间歇: 'jiàn xiē',
  翘首: 'qiáo shǒu',
  色调: 'sè diào',
  处决: 'chǔ jué',
  表率: 'biǎo shuài',
  尺子: 'chǐ zi',
  招降: 'zhāo xiáng',
  称职: 'chèn zhí',
  斗篷: 'dǒu peng',
  铺子: 'pù zi',
  底子: 'dǐ zi',
  负载: 'fù zài',
  干警: 'gàn jǐng',
  倒数: 'dào shǔ',
  将官: 'jiàng guān',
  锄头: 'chú tou',
  归降: 'guī xiáng',
  疟疾: 'nüè ji',
  唠叨: 'láo dao',
  限量: 'xiàn liàng',
  屏息: 'bǐng xī',
  重逢: 'chóng féng',
  器乐: 'qì yuè',
  氢弹: 'qīng dàn',
  脖颈: 'bó gěng',
  妃子: 'fēi zi',
  处事: 'chǔ shì',
  参量: 'cān liàng',
  轻率: 'qīng shuài',
  缥缈: 'piāo miǎo',
  幸得: 'xìng de',
  中奖: 'zhòng jiǎng',
  才干: 'cái gàn',
  施舍: 'shī shě',
  卷子: 'juǎn zi',
  游说: 'yóu shuì',
  巷子: 'xiàng zi',
  膀胱: 'páng guāng',
  切勿: 'qiē wù',
  看管: 'kān guǎn',
  风头: 'fēng tou',
  精干: 'jīng gàn',
  高差: 'gāo chā',
  恐吓: 'kǒng hè',
  扁担: 'biǎn dàn',
  给养: 'jǐ yǎng',
  格子: 'gé zi',
  供需: 'gōng xū',
  反差: 'fǎn chā',
  飞弹: 'fēi dàn',
  微薄: 'wēi bó',
  发型: 'fà xíng',
  即兴: 'jí xìng',
  攒动: 'cuán dòng',
  间或: 'jiàn huò',
  浅薄: 'qiǎn bó',
  乐章: 'yuè zhāng',
  顺差: 'shùn chā',
  调子: 'diào zi',
  相位: 'xiàng wèi',
  转子: 'zhuàn zǐ',
  劲旅: 'jìng lǚ',
  咔嚓: 'kā chā',
  了事: 'liǎo shì',
  转悠: 'zhuàn you',
  芍药: 'sháo yao',
  当铺: 'dàng pù',
  爪子: 'zhuǎ zi',
  单子: 'dān zi',
  好战: 'hào zhàn',
  燕麦: 'yàn mài',
  只许: 'zhǐ xǔ',
  干练: 'gàn liàn',
  女将: 'nǚ jiàng',
  酒量: 'jiǔ liàng',
  划船: 'huá chuán',
  伎俩: 'jì liǎng',
  挑拨: 'tiǎo bō',
  少校: 'shào xiào',
  着落: 'zhuó luò',
  憎恶: 'zēng wù',
  刻薄: 'kè bó',
  口角: 'kǒu jué',
  马尾: 'mǎ yǐ',
  要挟: 'yāo xié',
  用处: 'yòng chǔ',
  还手: 'huán shǒu',
  模具: 'mú jù',
  执著: 'zhí zhuó',
  喝令: 'hè lìng',
  争得: 'zhēng de',
  保长: 'bǎo zhǎng',
  吸着: 'xī zhuó',
  症结: 'zhēng jié',
  公转: 'gōng zhuàn',
  校勘: 'jiào kān',
  重提: 'chóng tí',
  扫兴: 'sǎo xìng',
  舞曲: 'wǔ qǔ',
  铺盖: 'pū gài',
  长史: 'zhǎng shǐ',
  差价: 'chā jià',
  压根: 'yà gēn',
  怔住: 'zhèng zhù',
  强人: 'qiǎng rén',
  应允: 'yīng yǔn',
  切入: 'qiē rù',
  战将: 'zhàn jiàng',
  年少: 'nián shào',
  舍身: 'shě shēn',
  执拗: 'zhí niù',
  处世: 'chǔ shì',
  中风: 'zhòng fēng',
  等量: 'děng liàng',
  放量: 'fàng liàng',
  腔调: 'qiāng diào',
  老少: 'lǎo shào',
  没入: 'mò rù',
  瓜葛: 'guā gé',
  将帅: 'jiàng shuài',
  车载: 'chē zài',
  窝囊: 'wō nāng',
  长进: 'zhǎng jìn',
  可汗: 'kè hán',
  并州: 'bīng zhōu',
  供销: 'gōng xiāo',
  切片: 'qiē piàn',
  差事: 'chāi shì',
  知会: 'zhī hui',
  鹰爪: 'yīng zhǎo',
  处女: 'chǔ nǚ',
  切磋: 'qiē cuō',
  日头: 'rì tou',
  押解: 'yā jiè',
  滋长: 'zī zhǎng',
  道观: 'dào guàn',
  脚色: 'jué sè',
  当量: 'dāng liàng',
  婆家: 'pó jia',
  缘分: 'yuán fèn',
  空闲: 'kòng xián',
  曲牌: 'qǔ pái',
  好色: 'hào sè',
  行会: 'háng huì',
  怒喝: 'nù hè',
  笼统: 'lǒng tǒng',
  边塞: 'biān sài',
  何曾: 'hé zēng',
  重合: 'chóng hé',
  插曲: 'chā qǔ',
  零散: 'líng sǎn',
  轰隆: 'hōng lōng',
  化子: 'huā zi',
  内蒙: 'nèi měng',
  数落: 'shǔ luo',
  逆差: 'nì chā',
  牟利: 'móu lì',
  栅栏: 'zhà lan',
  中标: 'zhòng biāo',
  调档: 'diào dàng',
  佝偻: 'gōu lóu',
  场子: 'chǎng zi',
  甲壳: 'jiǎ qiào',
  重温: 'chóng wēn',
  炮制: 'páo zhì',
  返还: 'fǎn huán',
  自传: 'zì zhuàn',
  高调: 'gāo diào',
  词曲: 'cí qǔ',
  受难: 'shòu nàn',
  殷红: 'yān hóng',
  要约: 'yāo yuē',
  固着: 'gù zhuó',
  强求: 'qiǎng qiú',
  本相: 'běn xiàng',
  骄横: 'jiāo hèng',
  草率: 'cǎo shuài',
  气闷: 'qì mèn',
  着色: 'zhuó sè',
  宁肯: 'nìng kěn',
  兴头: 'xìng tou',
  拘泥: 'jū nì',
  夹角: 'jiā jiǎo',
  发髻: 'fà jì',
  猛将: 'měng jiàng',
  劫难: 'jié nàn',
  约摸: 'yuē mo',
  拖累: 'tuō lěi',
  呢绒: 'ní róng',
  钻探: 'zuān tàn',
  夹层: 'jiā céng',
  把子: 'bà zi',
  落魄: 'luò tuò',
  巷道: 'xiàng dào',
  运量: 'yùn liàng',
  头里: 'tóu li',
  解闷: 'jiě mèn',
  空儿: 'kòng ér',
  估摸: 'gū mo',
  好客: 'hào kè',
  小曲: 'xiǎo qǔ',
  折衷: 'shé zhōng',
  钻孔: 'zuān kǒng',
  序曲: 'xù qǔ',
  糊弄: 'hù nong',
  荥阳: 'xíng yáng',
  道行: 'dào héng',
  烦闷: 'fán mèn',
  仓卒: 'cāng cù',
  分叉: 'fēn chà',
  曲率: 'qǔ lǜ',
  相片: 'xiàng piān',
  内行: 'nèi háng',
  厂子: 'chǎng zi',
  小调: 'xiǎo diào',
  少阳: 'shào yáng',
  受降: 'shòu xiáng',
  染坊: 'rǎn fáng',
  胳臂: 'gē bei',
  将门: 'jiàng mén',
  模板: 'mú bǎn',
  配给: 'pèi jǐ',
  为伍: 'wéi wǔ',
  跟头: 'gēn tou',
  划算: 'huá suàn',
  累赘: 'léi zhui',
  哄笑: 'hōng xiào',
  晕眩: 'yūn xuàn',
  干掉: 'gàn diào',
  缝制: 'féng zhì',
  难处: 'nán chǔ',
  着意: 'zhuó yì',
  蛮横: 'mán hèng',
  干将: 'gàn jiàng',
  奇数: 'jī shù',
  短发: 'duǎn fà',
  生还: 'shēng huán',
  还清: 'huán qīng',
  看护: 'kān hù',
  直率: 'zhí shuài',
  奏乐: 'zòu yuè',
  载客: 'zài kè',
  专横: 'zhuān hèng',
  湮没: 'yān mò',
  空格: 'kòng gé',
  铺垫: 'pū diàn',
  良将: 'liáng jiàng',
  哗啦: 'huā lā',
  散漫: 'sǎn màn',
  脱发: 'tuō fà',
  送还: 'sòng huán',
  埋没: 'mái mò',
  累及: 'lěi jí',
  薄雾: 'bó wù',
  调离: 'diào lí',
  舌苔: 'shé tāi',
  机长: 'jī zhǎng',
  栓塞: 'shuān sè',
  配角: 'pèi jué',
  切口: 'qiē kǒu',
  创口: 'chuāng kǒu',
  哈欠: 'hā qian',
  实弹: 'shí dàn',
  铺平: 'pū píng',
  哈达: 'hǎ dá',
  懒散: 'lǎn sǎn',
  实干: 'shí gàn',
  填空: 'tián kòng',
  刁钻: 'diāo zuān',
  乐师: 'yuè shī',
  量变: 'liàng biàn',
  诱降: 'yòu xiáng',
  搪塞: 'táng sè',
  征调: 'zhēng diào',
  夹道: 'jiā dào',
  干咳: 'gān ké',
  止咳: 'zhǐ ké',
  乐工: 'yuè gōng',
  商行: 'shāng háng',
  划过: 'huá guò',
  着火: 'zháo huǒ',
  更正: 'gēng zhèng',
  给付: 'jǐ fù',
  空子: 'kòng zi',
  哪吒: 'né zhā',
  散曲: 'sǎn qǔ',
  行规: 'háng guī',
  正着: 'zhèng zháo',
  刁难: 'diāo nàn',
  刷子: 'shuā zi',
  丧葬: 'sāng zàng',
  夹带: 'jiā dài',
  安分: 'ān fèn',
  中意: 'zhòng yì',
  长孙: 'zhǎng sūn',
  校订: 'jiào dìng',
  卷曲: 'juǎn qū',
  载运: 'zài yùn',
  投弹: 'tóu dàn',
  柞蚕: 'zuò cán',
  份量: 'fèn liàng',
  外行: 'wài háng',
  调换: 'diào huàn',
  了然: 'liǎo rán',
  咧嘴: 'liě zuǐ',
  典当: 'diǎn dàng',
  寒假: 'hán jià',
  长兄: 'zhǎng xiōng',
  给水: 'jǐ shuǐ',
  须发: 'xū fà',
  枝干: 'zhī gàn',
  属相: 'shǔ xiang',
  哄抢: 'hōng qiǎng',
  刻划: 'kè huá',
  手把: 'shǒu bà',
  塞子: 'sāi zi',
  单干: 'dān gàn',
  还乡: 'huán xiāng',
  兆头: 'zhào tou',
  寺观: 'sì guàn',
  督率: 'dū shuài',
  受累: 'shòu lěi',
  天台: 'tiān tāi',
  啊哈: 'ā hā',
  割舍: 'gē shě',
  抹布: 'mā bù',
  好恶: 'hào wù',
  下处: 'xià chǔ',
  消长: 'xiāo zhǎng',
  离间: 'lí jiàn',
  准头: 'zhǔn tou',
  校对: 'jiào duì',
  什物: 'shí wù',
  番禺: 'pān yú',
  佛爷: 'fó ye',
  吗啡: 'mǎ fēi',
  盐分: 'yán fèn',
  当月: 'dàng yuè',
  虎将: 'hǔ jiàng',
  薄荷: 'bò he',
  独处: 'dú chǔ',
  空位: 'kòng wèi',
  铺路: 'pū lù',
  乌拉: 'wū lā',
  调回: 'diào huí',
  来头: 'lái tou',
  闲散: 'xián sǎn',
  胶卷: 'jiāo juǎn',
  冒失: 'mào shi',
  干劲: 'gàn jìn',
  弦乐: 'xián yuè',
  行伍: 'háng wǔ',
  相国: 'xiàng guó',
  丹参: 'dān shēn',
  助兴: 'zhù xìng',
  铺开: 'pū kāi',
  次长: 'cì zhǎng',
  发卡: 'fà qiǎ',
  拮据: 'jié jū',
  刹车: 'shā chē',
  生发: 'shēng fà',
  重播: 'chóng bō',
  缝合: 'féng hé',
  音量: 'yīn liàng',
  少尉: 'shào wèi',
  殉难: 'xùn nàn',
  冲压: 'chòng yā',
  苍劲: 'cāng jìng',
  厚薄: 'hòu bó',
  威吓: 'wēi hè',
  外相: 'wài xiàng',
  曲谱: 'qǔ pǔ',
  呼号: 'hū háo',
  着迷: 'zháo mí',
  挑担: 'tiāo dàn',
  纹路: 'wén lu',
  还俗: 'huán sú',
  强横: 'qiáng hèng',
  着数: 'zhāo shù',
  国难: 'guó nàn',
  降顺: 'xiáng shùn',
  挑明: 'tiǎo míng',
  眯缝: 'mī feng',
  分内: 'fèn nèi',
  更衣: 'gēng yī',
  软和: 'ruǎn huo',
  尽兴: 'jìn xìng',
  号子: 'hào zi',
  爪牙: 'zhǎo yá',
  败将: 'bài jiàng',
  猜中: 'cāi zhòng',
  结扎: 'jié zā',
  没空: 'méi kòng',
  夹缝: 'jiā fèng',
  拾掇: 'shí duo',
  掺和: 'chān huo',
  簸箕: 'bò ji',
  电量: 'diàn liàng',
  荷载: 'hè zǎi',
  调式: 'diào shì',
  处身: 'chǔ shēn',
  打手: 'dǎ shou',
  弹弓: 'dàn gōng',
  横蛮: 'hèng mán',
  能干: 'néng gàn',
  校点: 'jiào diǎn',
  加载: 'jiā zài',
  干校: 'gàn xiào',
  哄传: 'hōng chuán',
  校注: 'jiào zhù',
  淤塞: 'yū sè',
  马扎: 'mǎ zhá',
  月氏: 'yuè zhī',
  高干: 'gāo gàn',
  经传: 'jīng zhuàn',
  曾孙: 'zēng sūn',
  好斗: 'hào dòu',
  关卡: 'guān qiǎ',
  逃奔: 'táo bèn',
  磨蹭: 'mó ceng',
  牟取: 'móu qǔ',
  颤栗: 'zhàn lì',
  蚂蚱: 'mà zha',
  撮合: 'cuō he',
  趔趄: 'liè qie',
  摔打: 'shuāi dá',
  台子: 'tái zi',
  分得: 'fēn de',
  粘着: 'nián zhuó',
  采邑: 'cài yì',
  散装: 'sǎn zhuāng',
  婀娜: 'ē nuó',
  兴味: 'xìng wèi',
  行头: 'xíng tou',
  气量: 'qì liàng',
  调运: 'diào yùn',
  处治: 'chǔ zhì',
  乐音: 'yuè yīn',
  组曲: 'zǔ qǔ',
  充塞: 'chōng sè',
  恫吓: 'dòng hè',
  论调: 'lùn diào',
  相中: 'xiāng zhòng',
  民乐: 'mín yuè',
  炮仗: 'pào zhang',
  丧服: 'sāng fú',
  骁将: 'xiāo jiàng',
  量刑: 'liàng xíng',
  缝补: 'féng bǔ',
  财会: 'cái kuài',
  大干: 'dà gàn',
  呱呱: 'gū gū',
  历数: 'lì shǔ',
  校场: 'jiào chǎng',
  塞北: 'sài běi',
  识相: 'shí xiàng',
  辱没: 'rǔ mò',
  鲜亮: 'xiān liang',
  语塞: 'yǔ sè',
  露脸: 'lòu liǎn',
  凉快: 'liáng kuai',
  腰杆: 'yāo gǎn',
  溜达: 'liū da',
  嘎嘎: 'gā gā',
  公干: 'gōng gàn',
  桔梗: 'jié gěng',
  挑逗: 'tiǎo dòu',
  看门: 'kān mén',
  海难: 'hǎi nàn',
  乐歌: 'yuè gē',
  拓片: 'tà piàn',
  挑动: 'tiǎo dòng',
  准将: 'zhǔn jiàng',
  落难: 'luò nàn',
  遒劲: 'qiú jìng',
  磨坊: 'mò fáng',
  逶迤: 'wēi yí',
  搅和: 'jiǎo huo',
  摩挲: 'mó suō',
  作弄: 'zuō nòng',
  苗头: 'miáo tou',
  打颤: 'dǎ zhàn',
  大藏: 'dà zàng',
  畜牲: 'chù sheng',
  勾搭: 'gōu da',
  树荫: 'shù yīn',
  树杈: 'shù chà',
  铁杆: 'tiě gǎn',
  将相: 'jiàng xiàng',
  份子: 'fèn zi',
  视差: 'shì chā',
  绿荫: 'lǜ yīn',
  枪杆: 'qiāng gǎn',
  缝纫: 'féng rèn',
  愁闷: 'chóu mèn',
  点将: 'diǎn jiàng',
  华佗: 'huà tuó',
  劲射: 'jìng shè',
  箱笼: 'xiāng lǒng',
  终了: 'zhōng liǎo',
  鬓发: 'bìn fà',
  结巴: 'jiē ba',
  苦干: 'kǔ gàn',
  看家: 'kān jiā',
  正旦: 'zhēng dàn',
  中肯: 'zhòng kěn',
  厦门: 'xià mén',
  东莞: 'dōng guǎn',
  食量: 'shí liàng',
  宫调: 'gōng diào',
  间作: 'jiàn zuò',
  弹片: 'dàn piàn',
  差池: 'chā chí',
  漂白: 'piǎo bái',
  杠子: 'gàng zi',
  调处: 'tiáo chǔ',
  好动: 'hào dòng',
  转炉: 'zhuàn lú',
  屏气: 'bǐng qì',
  夹板: 'jiā bǎn',
  哀乐: 'āi yuè',
  干道: 'gàn dào',
  苦处: 'kǔ chǔ',
  劈柴: 'pǐ chái',
  长势: 'zhǎng shì',
  天华: 'tiān huā',
  共处: 'gòng chǔ',
  校验: 'jiào yàn',
  出塞: 'chū sài',
  磨盘: 'mò pán',
  萎靡: 'wěi mǐ',
  奔丧: 'bēn sāng',
  唱和: 'chàng hè',
  大调: 'dà diào',
  非分: 'fēi fèn',
  钻营: 'zuān yíng',
  夹子: 'jiā zi',
  超载: 'chāo zài',
  更始: 'gēng shǐ',
  铃铛: 'líng dang',
  披散: 'pī sǎn',
  遭难: 'zāo nàn',
  发还: 'fā huán',
  转轮: 'zhuàn lún',
  横财: 'hèng cái',
  泡桐: 'pāo tóng',
  抛撒: 'pāo sǎ',
  天呀: 'tiān yā',
  糊糊: 'hū hū',
  躯壳: 'qū qiào',
  通量: 'tōng liàng',
  奉还: 'fèng huán',
  午觉: 'wǔ jiào',
  闷棍: 'mèn gùn',
  浪头: 'làng tou',
  砚台: 'yàn tāi',
  油坊: 'yóu fáng',
  学长: 'xué zhǎng',
  过载: 'guò zài',
  笔调: 'bǐ diào',
  衣被: 'yì bèi',
  畜产: 'xù chǎn',
  打更: 'dǎ gēng',
  调阅: 'diào yuè',
  蛮干: 'mán gàn',
  曾祖: 'zēng zǔ',
  本行: 'běn háng',
  提干: 'tí gàn',
  变调: 'biàn diào',
  覆没: 'fù mò',
  模子: 'mú zi',
  乐律: 'yuè lǜ',
  称心: 'chèn xīn',
  木杆: 'mù gǎn',
  套曲: 'tào qǔ',
  重印: 'chóng yìn',
  自省: 'zì xǐng',
  提调: 'tí diào',
  看相: 'kàn xiàng',
  芋头: 'yù tou',
  下切: 'xià qiē',
  塞上: 'sài shàng',
  铺张: 'pū zhāng',
  藤蔓: 'téng wàn',
  薄幸: 'bó xìng',
  非难: 'fēi nàn',
  解数: 'xiè shù',
  褪去: 'tùn qù',
  霰弹: 'xiàn dàn',
  柚木: 'yóu mù',
  痕量: 'hén liàng',
  雅乐: 'yǎ yuè',
  号哭: 'háo kū',
  诈降: 'zhà xiáng',
  猪圈: 'zhū juàn',
  咋舌: 'zé shé',
  铣床: 'xǐ chuáng',
  防弹: 'fáng dàn',
  健将: 'jiàn jiàng',
  丽水: 'lí shuǐ',
  削发: 'xuē fà',
  空当: 'kòng dāng',
  多相: 'duō xiàng',
  鲜见: 'xiǎn jiàn',
  划桨: 'huá jiǎng',
  载波: 'zài bō',
  跳蚤: 'tiào zao',
  俏皮: 'qiào pi',
  吧嗒: 'bā dā',
  结发: 'jié fà',
  了断: 'liǎo duàn',
  同调: 'tóng diào',
  石磨: 'shí mò',
  时差: 'shí chā',
  鼻塞: 'bí sè',
  挑子: 'tiāo zi',
  推磨: 'tuī mò',
  武侯: 'wǔ hòu',
  抹煞: 'mǒ shā',
  调转: 'diào zhuǎn',
  籍没: 'jí mò',
  测度: 'cè duó',
  还债: 'huán zhài',
  调演: 'diào yǎn',
  分划: 'fēn huá',
  奇偶: 'jī ǒu',
  断喝: 'duàn hè',
  闷雷: 'mèn léi',
  狼藉: 'láng jí',
  饭量: 'fàn liàng',
  还礼: 'huán lǐ',
  转调: 'zhuǎn diào',
  星相: 'xīng xiàng',
  手相: 'shǒu xiàng',
  配乐: 'pèi yuè',
  盖头: 'gài tou',
  连杆: 'lián gǎn',
  簿记: 'bù jì',
  刀把: 'dāo bà',
  量词: 'liàng cí',
  名角: 'míng jué',
  步调: 'bù diào',
  校本: 'jiào běn',
  曲江: 'qǔ jiāng',
  账簿: 'zhàng bù',
  隽永: 'juàn yǒng',
  哈罗: 'hā luo',
  稍为: 'shāo wéi',
  易传: 'yì zhuàn',
  乐谱: 'yuè pǔ',
  牵累: 'qiān lěi',
  答理: 'dā li',
  喝斥: 'hè chì',
  吟哦: 'yín é',
  干渠: 'gàn qú',
  海量: 'hǎi liàng',
  精当: 'jīng dàng',
  着床: 'zhuó chuáng',
  月相: 'yuè xiàng',
  庶几: 'shù jī',
  宫观: 'gōng guàn',
  论处: 'lùn chǔ',
  征辟: 'zhēng bì',
  厚朴: 'hòu pò',
  介壳: 'jiè qiào',
  吭哧: 'kēng chi',
  咯血: 'kǎ xiě',
  铺陈: 'pū chén',
  重生: 'chóng shēng',
  乐理: 'yuè lǐ',
  哀号: 'āi háo',
  藏历: 'zàng lì',
  琴曲: 'qín qǔ',
  神曲: 'shén qǔ',
  刚劲: 'gāng jìng',
  削平: 'xuē píng',
  浓荫: 'nóng yīn',
  城垛: 'chéng duǒ',
  当差: 'dāng chāi',
  正传: 'zhèng zhuàn',
  并处: 'bìng chǔ',
  空难: 'kōng nàn',
  创面: 'chuāng miàn',
  旦角: 'dàn jué',
  薄礼: 'bó lǐ',
  晃荡: 'huàng dang',
  臊子: 'sào zi',
  家什: 'jiā shí',
  闷头: 'mèn tóu',
  美发: 'měi fà',
  度数: 'dù shu',
  着凉: 'zháo liáng',
  闯将: 'chuǎng jiàng',
  几案: 'jī àn',
  姘头: 'pīn tou',
  急难: 'jí nàn',
  差数: 'chā shù',
  散碎: 'sǎn suì',
  壅塞: 'yōng sè',
  寒颤: 'hán zhàn',
  牵强: 'qiān qiǎng',
  无间: 'wú jiàn',
  轮转: 'lún zhuàn',
  号叫: 'háo jiào',
  铺排: 'pū pái',
  降伏: 'xiáng fú',
  轧钢: 'zhá gāng',
  东阿: 'dōng ē',
  病假: 'bìng jià',
  累加: 'lěi jiā',
  梗塞: 'gěng sè',
  弹夹: 'dàn jiā',
  钻心: 'zuān xīn',
  晃眼: 'huǎng yǎn',
  魔爪: 'mó zhǎo',
  标量: 'biāo liàng',
  憋闷: 'biē mèn',
  猜度: 'cāi duó',
  处士: 'chǔ shì',
  官差: 'guān chāi',
  讨还: 'tǎo huán',
  长门: 'zhǎng mén',
  馏分: 'liú fèn',
  里弄: 'lǐ lòng',
  色相: 'sè xiàng',
  雅兴: 'yǎ xìng',
  角力: 'jué lì',
  弹坑: 'dàn kēng',
  枝杈: 'zhī chà',
  夹具: 'jiā jù',
  处刑: 'chǔ xíng',
  悍将: 'hàn jiàng',
  好学: 'hào xué',
  好好: 'hǎo hǎo',
  银发: 'yín fà',
  扫把: 'sào bǎ',
  法相: 'fǎ xiàng',
  贵干: 'guì gàn',
  供气: 'gōng qì',
  空余: 'kòng yú',
  捆扎: 'kǔn zā',
  瘠薄: 'jí bó',
  浆糊: 'jiàng hu',
  嘎吱: 'gā zhī',
  调令: 'diào lìng',
  法帖: 'fǎ tiè',
  淋病: 'lìn bìng',
  调派: 'diào pài',
  转盘: 'zhuàn pán',
  供稿: 'gōng gǎo',
  差官: 'chāi guān',
  忧闷: 'yōu mèn',
  教长: 'jiào zhǎng',
  重唱: 'chóng chàng',
  酒兴: 'jiǔ xìng',
  乐坛: 'yuè tán',
  花呢: 'huā ní',
  叱喝: 'chì hè',
  膀臂: 'bǎng bì',
  得空: 'dé kòng',
  转圈: 'zhuàn quān',
  横暴: 'hèng bào',
  哄抬: 'hōng tái',
  引吭: 'yǐn háng',
  载货: 'zài huò',
  中计: 'zhòng jì',
  官长: 'guān zhǎng',
  相面: 'xiàng miàn',
  看头: 'kàn tou',
  盼头: 'pàn tou',
  意兴: 'yì xìng',
  军乐: 'jūn yuè',
  累次: 'lěi cì',
  骨嘟: 'gū dū',
  燕赵: 'yān zhào',
  报丧: 'bào sāng',
  弥撒: 'mí sa',
  挨斗: 'ái dòu',
  扁舟: 'piān zhōu',
  丑角: 'chǒu jué',
  吊丧: 'diào sāng',
  强将: 'qiáng jiàng',
  行号: 'háng háo',
  重奏: 'chóng zòu',
  发辫: 'fà biàn',
  着魔: 'zháo mó',
  着法: 'zhāo fǎ',
  盛放: 'chéng fàng',
  填塞: 'tián sè',
  凶横: 'xiōng hèng',
  稽首: 'qǐ shǒu',
  碑帖: 'bēi tiè',
  冲量: 'chōng liàng',
  发菜: 'fà cài',
  假发: 'jiǎ fà',
  翻卷: 'fān juǎn',
  小量: 'xiǎo liàng',
  胶着: 'jiāo zhuó',
  里子: 'lǐ zi',
  调调: 'diào diao',
  散兵: 'sǎn bīng',
  高挑: 'gāo tiǎo',
  播撒: 'bō sǎ',
  夹心: 'jiā xīn',
  扇动: 'shān dòng',
  叨扰: 'tāo rǎo',
  霓裳: 'ní cháng',
  捻子: 'niǎn zi',
  弥缝: 'mí féng',
  撒布: 'sǎ bù',
  元曲: 'yuán qǔ',
  场院: 'cháng yuàn',
  省亲: 'xǐng qīn',
  提拉: 'dī le',
  惯量: 'guàn liàng',
  强逼: 'qiǎng bī',
  强征: 'qiǎng zhēng',
  晕车: 'yùn chē',
  数道: 'shǔ dào',
  带累: 'dài lěi',
  拓本: 'tà běn',
  嫌恶: 'xián wù',
  宿将: 'sù jiàng',
  龟裂: 'jūn liè',
  缠夹: 'chán jiā',
  发式: 'fà shì',
  隔扇: 'gé shān',
  行货: 'háng huò',
  天分: 'tiān fèn',
  癖好: 'pǐ hào',
  四通: 'sì tòng',
  白术: 'bái zhú',
  划伤: 'huá shāng',
  角斗: 'jué dòu',
  听差: 'tīng chāi',
  岁差: 'suì chā',
  丧礼: 'sāng lǐ',
  脉脉: 'mò mò',
  削瘦: 'xuē shòu',
  撒播: 'sǎ bō',
  莎草: 'suō cǎo',
  犍为: 'qián wéi',
  调头: 'diào tóu',
  龙卷: 'lóng juǎn',
  外调: 'wài diào',
  字帖: 'zì tiè',
  卷发: 'juǎn fà',
  揣度: 'chuǎi duó',
  洋相: 'yáng xiàng',
  散光: 'sǎn guāng',
  骨碌: 'gū lu',
  薄命: 'bó mìng',
  笼头: 'lóng tou',
  咽炎: 'yān yán',
  碌碡: 'liù zhou',
  片儿: 'piān er',
  纤手: 'qiàn shǒu',
  散体: 'sǎn tǐ',
  内省: 'nèi xǐng',
  强留: 'qiǎng liú',
  解送: 'jiè sòng',
  反间: 'fǎn jiàn',
  少壮: 'shào zhuàng',
  留空: 'liú kòng',
  告假: 'gào jià',
  咳血: 'ké xiě',
  薄暮: 'bó mù',
  铺轨: 'pū guǐ',
  磨削: 'mó xuē',
  治丧: 'zhì sāng',
  叉子: 'chā zi',
  哄动: 'hōng dòng',
  蛾子: 'é zi',
  出落: 'chū là',
  股长: 'gǔ zhǎng',
  贵处: 'guì chǔ',
  还魂: 'huán hún',
  例假: 'lì jià',
  曲池: 'qǔ chí',
  刹住: 'shā zhù',
  身量: 'shēn liàng',
  懂行: 'dǒng háng',
  同好: 'tóng hào',
  模量: 'mó liàng',
  更生: 'gēng shēng',
  服丧: 'fú sāng',
  率直: 'shuài zhí',
  字模: 'zì mú',
  散架: 'sǎn jià',
  答腔: 'dā qiāng',
  交恶: 'jiāo wù',
  薄情: 'bó qíng',
  眼泡: 'yǎn pāo',
  袅娜: 'niǎo nuó',
  草垛: 'cǎo duǒ',
  冲劲: 'chòng jìn',
  呢喃: 'ní nán',
  切中: 'qiè zhòng',
  挑灯: 'tiǎo dēng',
  还愿: 'huán yuàn',
  激将: 'jī jiàng',
  更鼓: 'gēng gǔ',
  没药: 'mò yào',
  难友: 'nàn yǒu',
  败兴: 'bài xìng',
  切面: 'qiē miàn',
  散户: 'sǎn hù',
  累进: 'lěi jìn',
  背带: 'bēi dài',
  秤杆: 'chèng gǎn',
  碾坊: 'niǎn fáng',
  簿子: 'bù zi',
  扳手: 'bān shou',
  铅山: 'yán shān',
  儒将: 'rú jiàng',
  重光: 'chóng guāng',
  剪发: 'jiǎn fà',
  行话: 'háng huà',
  长上: 'zhǎng shàng',
  小传: 'xiǎo zhuàn',
  压轴: 'yā zhòu',
  谱曲: 'pǔ qǔ',
  弱冠: 'ruò guàn',
  花卷: 'huā juǎn',
  横祸: 'hèng huò',
  夹克: 'jiā kè',
  光晕: 'guāng yùn',
  披靡: 'pī mǐ',
  对调: 'duì diào',
  夹持: 'jiā chí',
  空额: 'kòng é',
  平调: 'píng diào',
  铺床: 'pū chuáng',
  丧钟: 'sāng zhōng',
  作乐: 'zuò yuè',
  少府: 'shào fǔ',
  数数: 'shuò shuò',
  奔头: 'bèn tou',
  进给: 'jìn jǐ',
  率性: 'shuài xìng',
  乐子: 'lè zi',
  绑扎: 'bǎng zā',
  挑唆: 'tiǎo suō',
  漂洗: 'piǎo xǐ',
  夹墙: 'jiā qiáng',
  咳喘: 'ké chuǎn',
  乜斜: 'miē xie',
  错处: 'cuò chǔ',
  闷酒: 'mèn jiǔ',
  时调: 'shí diào',
  重孙: 'chóng sūn',
  经幢: 'jīng chuáng',
  圩场: 'xū cháng',
  调门: 'diào mén',
  花头: 'huā tou',
  划拉: 'huá la',
  套色: 'tào shǎi',
  粗率: 'cū shuài',
  相率: 'xiāng shuài',
  款识: 'kuǎn zhì',
  吁请: 'yù qǐng',
  荫蔽: 'yīn bì',
  文蛤: 'wén gé',
  嘀嗒: 'dī dā',
  调取: 'diào qǔ',
  交差: 'jiāo chāi',
  落子: 'lào zǐ',
  相册: 'xiàng cè',
  絮叨: 'xù dáo',
  落发: 'luò fà',
  异相: 'yì xiàng',
  浸没: 'jìn mò',
  角抵: 'jué dǐ',
  卸载: 'xiè zài',
  春卷: 'chūn juǎn',
  扎挣: 'zhá zheng',
  畜养: 'xù yǎng',
  吡咯: 'bǐ luò',
  垛子: 'duǒ zi',
  恶少: 'è shào',
  发际: 'fà jì',
  红苕: 'hóng sháo',
  糨糊: 'jiàng hù',
  哭丧: 'kū sang',
  稍息: 'shào xī',
  晕船: 'yùn chuán',
  校样: 'jiào yàng',
  外差: 'wài chāi',
  红曲: 'hóng qǔ',
  脚爪: 'jiǎo zhǎo',
  铺展: 'pū zhǎn',
  芫荽: 'yán sui',
  夹紧: 'jiā jǐn',
  尿泡: 'suī pào',
  丧乱: 'sāng luàn',
  凶相: 'xiōng xiàng',
  华发: 'huá fà',
  打场: 'dǎ cháng',
  云量: 'yún liàng',
  正切: 'zhèng qiē',
  留难: 'liú nàn',
  划拳: 'huá quán',
  划艇: 'huá tǐng',
  评传: 'píng zhuàn',
  拉纤: 'lā qiàn',
  句读: 'jù dòu',
  散剂: 'sǎn jì',
  骨殖: 'gǔ shi',
  塞音: 'sè yīn',
  铺叙: 'pū xù',
  阏氏: 'yān zhī',
  冷颤: 'lěng zhàn',
  煞住: 'shā zhù',
  夜曲: 'yè qǔ',
  少男: 'shào nán',
  格登: 'gē dēng',
  管乐: 'guǎn yuè',
  号啕: 'háo táo',
  纳降: 'nà xiáng',
  拥塞: 'yōng sè',
  万乘: 'wàn shèng',
  杆儿: 'gǎn ér',
  葛藤: 'gé téng',
  簿籍: 'bù jí',
  皮夹: 'pí jiā',
  校准: 'jiào zhǔn',
  行款: 'háng kuǎn',
  允当: 'yǔn dàng',
  器量: 'qì liàng',
  选调: 'xuǎn diào',
  扮相: 'bàn xiàng',
  干才: 'gàn cái',
  基干: 'jī gàn',
  三校: 'sān jiào',
  割切: 'gē qiē',
  国乐: 'guó yuè',
  卡壳: 'qiǎ ké',
  辟谷: 'bì gǔ',
  磨房: 'mò fáng',
  咿呀: 'yī yā',
  芥末: 'jiè mo',
  薄技: 'bó jì',
  产假: 'chǎn jià',
  诗兴: 'shī xìng',
  重出: 'chóng chū',
  转椅: 'zhuàn yǐ',
  酌量: 'zhuó liàng',
  簿册: 'bù cè',
  藏青: 'zàng qīng',
  的士: 'dí shì',
  调人: 'diào rén',
  解元: 'jiè yuán',
  茎干: 'jīng gàn',
  巨量: 'jù liàng',
  榔头: 'láng tou',
  率真: 'shuài zhēn',
  喷香: 'pèn xiāng',
  锁钥: 'suǒ yuè',
  虾蟆: 'há má',
  相图: 'xiàng tú',
  兴会: 'xìng huì',
  灶头: 'zào tou',
  重婚: 'chóng hūn',
  钻洞: 'zuān dòng',
  忖度: 'cǔn duó',
  党参: 'dǎng shēn',
  调温: 'diào wēn',
  杆塔: 'gǎn tǎ',
  葛布: 'gé bù',
  拱券: 'gǒng xuàn',
  夹生: 'jiā shēng',
  露馅: 'lòu xiàn',
  恰切: 'qià qiē',
  散见: 'sǎn jiàn',
  哨卡: 'shào qiǎ',
  烫发: 'tàng fà',
  体量: 'tǐ liàng',
  挺括: 'tǐng guā',
  系带: 'jì dài',
  相士: 'xiàng shì',
  羊圈: 'yáng juàn',
  转矩: 'zhuàn jǔ',
  吧台: 'bā tái',
  苍术: 'cāng zhú',
  菲薄: 'fěi bó',
  蛤蚧: 'gé jiè',
  蛤蜊: 'gé lí',
  瓜蔓: 'guā wàn',
  怪相: 'guài xiàng',
  罹难: 'lí nàn',
  临帖: 'lín tiè',
  女红: 'nǚ gōng',
  刨床: 'bào chuáng',
  翘楚: 'qiáo chǔ',
  数九: 'shǔ jiǔ',
  谈兴: 'tán xìng',
  心曲: 'xīn qǔ',
  雄劲: 'xióng jìng',
  扎染: 'zā rǎn',
  遮荫: 'zhē yīn',
  周正: 'zhōu zhēng',
  赚头: 'zhuàn tou',
  扒手: 'pá shǒu',
  搀和: 'chān huo',
  诚朴: 'chéng piáo',
  肚量: 'dù liàng',
  干结: 'gàn jié',
  工尺: 'gōng chě',
  家累: 'jiā lěi',
  曲水: 'qǔ shuǐ',
  沙参: 'shā shēn',
  挑花: 'tiǎo huā',
  行距: 'háng jù',
  阿门: 'ā mēn',
  背篓: 'bēi lǒu',
  瘪三: 'biē sān',
  裁处: 'cái chǔ',
  创痛: 'chuāng tòng',
  福相: 'fú xiàng',
  更动: 'gēng dòng',
  豪兴: 'háo xìng',
  还阳: 'huán yáng',
  还嘴: 'huán zuǐ',
  借调: 'jiè diào',
  卷云: 'juǎn yún',
  流弹: 'liú dàn',
  想头: 'xiǎng tou',
  削价: 'xuē jià',
  校阅: 'jiào yuè',
  雅量: 'yǎ liàng',
  别传: 'bié zhuàn',
  薄酒: 'bó jiǔ',
  春假: 'chūn jià',
  发妻: 'fà qī',
  哗哗: 'huā huā',
  宽绰: 'kuān chuo',
  了悟: 'liǎo wù',
  切花: 'qiē huā',
  审度: 'shěn duó',
  应许: 'yīng xǔ',
  转台: 'zhuàn tái',
  仔猪: 'zǐ zhū',
  裁量: 'cái liàng',
  藏戏: 'zàng xì',
  乘兴: 'chéng xìng',
  绸缪: 'chóu móu',
  摧折: 'cuī shé',
  调经: 'diào jīng',
  调职: 'diào zhí',
  缝缀: 'féng zhuì',
  骨朵: 'gū duǒ',
  核儿: 'hú ér',
  恒量: 'héng liàng',
  还价: 'huán jià',
  浑朴: 'hún piáo',
  苦差: 'kǔ chāi',
  面糊: 'miàn hù',
  曲张: 'qǔ zhāng',
  煞车: 'shā chē',
  省视: 'xǐng shì',
  什锦: 'shí jǐn',
  信差: 'xìn chāi',
  余切: 'yú qiē',
  攒眉: 'cuán méi',
  炸糕: 'zhá gāo',
  钻杆: 'zuàn gǎn',
  扒灰: 'pá huī',
  拌和: 'bàn huò',
  长调: 'cháng diào',
  大溜: 'dà liù',
  抖搂: 'dǒu lōu',
  飞转: 'fēi zhuàn',
  赴难: 'fù nàn',
  干仗: 'gàn zhàng',
  好胜: 'hào shèng',
  画片: 'huà piān',
  搅混: 'jiǎo gǔn',
  螺杆: 'luó gǎn',
  木模: 'mù mú',
  怒号: 'nù háo',
  频数: 'pín shuò',
  无宁: 'wú nìng',
  选曲: 'xuǎn qǔ',
  遗少: 'yí shào',
  邮差: 'yóu chāi',
  占卦: 'zhān guà',
  占星: 'zhān xīng',
  重审: 'chóng shěn',
  自量: 'zì liàng',
  调防: 'diào fáng',
  发廊: 'fà láng',
  反调: 'fǎn diào',
  缝子: 'fèng zi',
  更夫: 'gēng fū',
  骨子: 'gǔ zi',
  光杆: 'guāng gǎn',
  夹棍: 'jiā gùn',
  居丧: 'jū sāng',
  巨贾: 'jù gǔ',
  看押: 'kān yā',
  空转: 'kōng zhuàn',
  量力: 'liàng lì',
  蒙难: 'méng nàn',
  炮烙: 'páo luò',
  赔还: 'péi huán',
  扑扇: 'pū shān',
  散记: 'sǎn jì',
  散件: 'sǎn jiàn',
  删削: 'shān xuē',
  射干: 'yè gàn',
  条几: 'tiáo jī',
  偷空: 'tōu kòng',
  削壁: 'xuē bì',
  校核: 'jiào hé',
  阴干: 'yīn gàn',
  择菜: 'zhái cài',
  重九: 'chóng jiǔ',
  主调: 'zhǔ diào',
  自禁: 'zì jīn',
  吧唧: 'bā jī',
  便溺: 'biàn niào',
  词调: 'cí diào',
  叨咕: 'dáo gu',
  俚曲: 'lǐ qǔ',
  落枕: 'lào zhěn',
  铺砌: 'pū qì',
  刷白: 'shuà bái',
  委靡: 'wěi mǐ',
  系泊: 'jì bó',
  相马: 'xiàng mǎ',
  行辈: 'háng bèi',
  熨帖: 'yù tiē',
  转筋: 'zhuàn jīn',
  棒喝: 'bàng hè',
  傧相: 'bīn xiàng',
  镐头: 'gǎo tóu',
  间苗: 'jiàn miáo',
  乐池: 'yuè chí',
  卖相: 'mài xiàng',
  难为: 'nán wéi',
  屏弃: 'bǐng qì',
  铅弹: 'qiān dàn',
  切变: 'qiē biàn',
  请调: 'qǐng diào',
  曲度: 'qǔ dù',
  群氓: 'qún méng',
  散板: 'sǎn bǎn',
  省察: 'xǐng chá',
  事假: 'shì jià',
  纤绳: 'qiàn shéng',
  重影: 'chóng yǐng',
  耕种: 'gēng zhòng',
  种地: 'zhòng dì',
  种菜: 'zhòng cài',
  栽种: 'zāi zhòng',
  接种: 'jiē zhòng',
  垦种: 'kěn zhòng',
  种殖: 'zhòng zhí',
  种瓜: 'zhòng guā',
  种豆: 'zhòng dòu',
  种树: 'zhòng shù',
  睡着: 'shuì zháo',
  笼子: 'lóng zi',
  重启: 'chóng qǐ',
  重整: 'chóng zhěng',
  重弹: 'chóng tán',
  重足: 'chóng zú',
  重山: 'chóng shān',
  重游: 'chóng yóu',
  重峦: 'chóng luán',
  爷爷: 'yé ye',
  奶奶: 'nǎi nai',
  姥爷: 'lǎo ye',
  爸爸: 'bà ba',
  妈妈: 'mā ma',
  婶婶: 'shěn shen',
  舅舅: 'jiù jiu',
  姑姑: 'gū gu',
  叔叔: 'shū shu',
  姨夫: 'yí fu',
  舅母: 'jiù mu',
  姑父: 'gū fu',
  姐夫: 'jiě fu',
  婆婆: 'pó po',
  公公: 'gōng gong',
  舅子: 'jiù zi',
  姐姐: 'jiě jie',
  哥哥: 'gē ge',
  妹妹: 'mèi mei',
  妹夫: 'mèi fu',
  姨子: 'yí zi',
  宝宝: 'bǎo bao',
  娃娃: 'wá wa',
  孩子: 'hái zi',
  日子: 'rì zi',
  样子: 'yàng zi',
  狮子: 'shī zi',
  身子: 'shēn zi',
  架子: 'jià zi',
  嫂子: 'sǎo zi',
  鼻子: 'bí zi',
  亭子: 'tíng zi',
  折子: 'zhé zi',
  面子: 'miàn zi',
  脖子: 'bó zi',
  辈子: 'bèi zi',
  帽子: 'mào zi',
  拍子: 'pāi zi',
  柱子: 'zhù zi',
  辫子: 'biàn zi',
  鸽子: 'gē zi',
  房子: 'fáng zi',
  丸子: 'wán zi',
  摊子: 'tān zi',
  牌子: 'pái zi',
  胡子: 'hú zi',
  鬼子: 'guǐ zi',
  矮子: 'ǎi zi',
  鸭子: 'yā zi',
  小子: 'xiǎo zi',
  影子: 'yǐng zi',
  屋子: 'wū zi',
  对子: 'duì zi',
  点子: 'diǎn zi',
  本子: 'běn zi',
  种子: 'zhǒng zi',
  儿子: 'ér zi',
  兔子: 'tù zi',
  骗子: 'piàn zi',
  院子: 'yuàn zi',
  猴子: 'hóu zi',
  嗓子: 'sǎng zi',
  侄子: 'zhí zi',
  柿子: 'shì zi',
  钳子: 'qián zi',
  虱子: 'shī zi',
  瓶子: 'píng zi',
  豹子: 'bào zi',
  筷子: 'kuài zi',
  篮子: 'lán zi',
  绳子: 'shéng zi',
  嘴巴: 'zuǐ ba',
  耳朵: 'ěr duo',
  茄子: 'qié zi',
  蚌埠: 'bèng bù',
  崆峒: 'kōng tóng',
  琵琶: 'pí pa',
  蘑菇: 'mó gu',
  葫芦: 'hú lu',
  狐狸: 'hú li',
  桔子: 'jú zi',
  盒子: 'hé zi',
  桌子: 'zhuō zi',
  竹子: 'zhú zi',
  师傅: 'shī fu',
  衣服: 'yī fu',
  袜子: 'wà zi',
  杯子: 'bēi zi',
  刺猬: 'cì wei',
  麦子: 'mài zi',
  队伍: 'duì wu',
  知了: 'zhī liao',
  鱼儿: 'yú er',
  馄饨: 'hún tun',
  灯笼: 'dēng long',
  庄稼: 'zhuāng jia',
  聪明: 'cōng ming',
  镜子: 'jìng zi',
  银子: 'yín zi',
  盘子: 'pán zi',
  了却: 'liǎo què',
  力气: 'lì qi',
  席子: 'xí zi',
  林子: 'lín zi',
  朝霞: 'zhāo xiá',
  朝夕: 'zhāo xī',
  朝气: 'zhāo qì',
  翅膀: 'chì bǎng',
  省长: 'shěng zhǎng',
  臧否: 'zāng pǐ',
  否泰: 'pǐ tài',
  变得: 'biàn de',
  丈夫: 'zhàng fu',
  豆腐: 'dòu fu',
  笔杆: 'bǐ gǎn',
  枞阳: 'zōng yáng',
  行人: 'xíng rén',
  打着: 'dǎ zhe',
  第一: 'dì yī',
  万一: 'wàn yī',
  之一: 'zhī yī',
  统一: 'tǒng yī',
  如一: 'rú yī',
  初一: 'chū yī',
  一一: 'yī yī',
  高一: 'gāo yī',
  了了: 'liǎo liǎo',
  公了: 'gōng liǎo',
  私了: 'sī liǎo',
  成吉思汗: "chéng jí sī hán",
  四通八达: "sì tōng bā dá",
  一模一样: "yì mú yí yàng",
  青藏高原: "qīng zàng gāo yuán",
  阿弥陀佛: "ē mí tuó fó",
  解放思想: "jiè fàng sī xiǎng",
  所作所为: "suǒ zuò suǒ wéi",
  迷迷糊糊: "mí mí hu hū",
  荷枪实弹: "hè qiāng shí dàn",
  兴高采烈: "xìng gāo cǎi liè",
  无能为力: "wú néng wéi lì",
  布鲁塞尔: "bù lǔ sài ěr",
  为所欲为: "wéi suǒ yù wéi",
  克什米尔: "kè shí mǐ ěr",
  没完没了: "méi wán méi liǎo",
  不为人知: "bù wéi rén zhī",
  结结巴巴: "jiē jiē bā bā",
  前仆后继: "qián pū hòu jì",
  各行各业: "gè háng gè yè",
  铺天盖地: "pū tiān gài dì",
  直截了当: "zhí jié liǎo dàng",
  供不应求: "gōng bú yìng qiú",
  御史大夫: "yù shǐ dà fū",
  不为瓦全: "bù wéi wǎ quán",
  不可收拾: "bù kě shōu shi",
  胡作非为: "hú zuò fēi wéi",
  分毫不差: "fēn háo bú chà",
  模模糊糊: "mó mó hu hū",
  不足为奇: "bù zú wéi qí",
  如之奈何: "rú zhī nai hé",
  悄无声息: "qiǎo wú shēng xī",
  了如指掌: "liǎo rú zhǐ zhǎng",
  深恶痛绝: "shēn wù tòng jué",
  高高兴兴: "gāo gāo xìng xìng",
  唉声叹气: "āi shēng tàn qì",
  汉藏语系: "hàn zàng yǔ xì",
  处心积虑: "chǔ xīn jī lǜ",
  泣不成声: "qì bù chéng shēng",
  半夜三更: "bàn yè sān gēng",
  失魂落魄: "shī hún luò pò",
  二十八宿: "èr shí bā xiù",
  转来转去: "zhuàn lái zhuàn qù",
  数以万计: "shǔ yǐ wàn jì",
  相依为命: "xiāng yī wéi mìng",
  恋恋不舍: "liàn liàn bù shě",
  屈指可数: "qū zhǐ kě shǔ",
  神出鬼没: "shén chū guǐ mò",
  结结实实: "jiē jiē shí shí",
  有的放矢: "yǒu dì fàng shǐ",
  叽哩咕噜: "jī lǐ gū lū",
  调兵遣将: "diào bīng qiǎn jiàng",
  载歌载舞: "zài gē zài wǔ",
  转危为安: "zhuǎn wēi wéi ān",
  踏踏实实: "tā tā shi shí",
  桑给巴尔: "sāng jǐ bā ěr",
  装模作样: "zhuāng mú zuò yàng",
  见义勇为: "jiàn yì yǒng wéi",
  相差无几: "xiāng chā wú jǐ",
  叹为观止: "tàn wéi guān zhǐ",
  闷闷不乐: "mèn mèn bú lè",
  喜怒哀乐: "xǐ nù āi lè",
  鲜为人知: "xiǎn wéi rén zhī",
  张牙舞爪: "zhāng yá wǔ zhǎo",
  为非作歹: "wéi fēi zuò dǎi",
  含糊其辞: "hán hú qí cí",
  疲于奔命: "pí yú bēn mìng",
  勉为其难: "miǎn wéi qí nán",
  依依不舍: "yī yī bù shě",
  顶头上司: "dǐng tóu shàng si",
  不着边际: "bù zhuó biān jì",
  大模大样: "dà mú dà yàng",
  寻欢作乐: "xún huān zuò lè",
  一走了之: "yì zǒu liǎo zhī",
  字里行间: "zì lǐ háng jiān",
  含含糊糊: "hán hán hu hū",
  数一数二: "shǔ yī shǔ èr",
  恰如其分: "qià rú qí fèn",
  破涕为笑: "pò tì wéi xiào",
  深更半夜: "shēn gēng bàn yè",
  千差万别: "qiān chā wàn bié",
  数不胜数: "shǔ bú shèng shǔ",
  据为己有: "jù wéi jǐ yǒu",
  天旋地转: "tiān xuán dì zhuàn",
  养尊处优: "yǎng zūn chǔ yōu",
  玻璃纤维: "bō li xiān wéi",
  吵吵闹闹: "chāo chao nào nào",
  晕头转向: "yūn tóu zhuàn xiàng",
  土生土长: "tǔ shēng tǔ zhǎng",
  宁死不屈: "nìng sǐ bù qū",
  不省人事: "bù xǐng rén shì",
  尽力而为: "jìn lì ér wéi",
  精明强干: "jīng míng qiáng gàn",
  唠唠叨叨: "láo lao dāo dāo",
  叽叽喳喳: "jī ji zhā zhā",
  功不可没: "gōng bù kě mò",
  锲而不舍: "qiè ér bù shě",
  排忧解难: "pái yōu jiě nàn",
  稀里糊涂: "xī li hú tú",
  异曲同工: "yì qǔ tóng gōng",
  各有所长: "gè yǒu suǒ chéng",
  的的确确: "dí dí què què",
  哄堂大笑: "hōng táng dà xiào",
  听而不闻: "tīng ér bù wén",
  刀耕火种: "dāo gēng huǒ zhòng",
  内分泌腺: "nèi fèn mì xiàn",
  化险为夷: "huà xiǎn wéi yí",
  百发百中: "bǎi fā bǎi zhòng",
  重见天日: "chóng jiàn tiān rì",
  反败为胜: "fǎn bài wéi shèng",
  一了百了: "yì liǎo bǎi liǎo",
  大大咧咧: "dà da liē liē",
  心急火燎: "xīn jí huǒ liǎo",
  粗心大意: "cū xīn dà yi",
  鸡皮疙瘩: "jī pí gē da",
  夷为平地: "yí wéi píng dì",
  日积月累: "rì jī yuè lěi",
  设身处地: "shè shēn chǔ dì",
  投其所好: "tóu qí suǒ hào",
  间不容发: "jiān bù róng fà",
  人满为患: "rén mǎn wéi huàn",
  穷追不舍: "qióng zhuī bù shě",
  为时已晚: "wéi shí yǐ wǎn",
  如数家珍: "rú shǔ jiā zhēn",
  心里有数: "xīn lǐ yǒu shù",
  以牙还牙: "yǐ yá huán yá",
  神不守舍: "shén bù shǒu shě",
  孟什维克: "mèng shí wéi kè",
  各自为战: "gè zì wéi zhàn",
  怨声载道: "yuàn shēng zài dào",
  救苦救难: "jiù kǔ jiù nàn",
  好好先生: "hǎo hǎo xiān sheng",
  怪模怪样: "guài mú guài yàng",
  抛头露面: "pāo tóu lù miàn",
  游手好闲: "yóu shǒu hào xián",
  无所不为: "wú suǒ bù wéi",
  调虎离山: "diào hǔ lí shān",
  步步为营: "bù bù wéi yíng",
  好大喜功: "hào dà xǐ gōng",
  众矢之的: "zhòng shǐ zhī dì",
  长生不死: "cháng shēng bù sǐ",
  蔚为壮观: "wèi wéi zhuàng guān",
  不可胜数: "bù kě shèng shǔ",
  鬼使神差: "guǐ shǐ shén chāi",
  洁身自好: "jié shēn zì hào",
  敢作敢为: "gǎn zuò gǎn wéi",
  茅塞顿开: "máo sè dùn kāi",
  走马换将: "zǒu mǎ huàn jiàng",
  为时过早: "wéi shí guò zǎo",
  为人师表: "wéi rén shī biǎo",
  阴差阳错: "yīn chā yáng cuò",
  油腔滑调: "yóu qiāng huá diào",
  重蹈覆辙: "chóng dǎo fù zhé",
  骂骂咧咧: "mà ma liē liē",
  絮絮叨叨: "xù xù dāo dāo",
  如履薄冰: "rú lǚ bó bīng",
  损兵折将: "sǔn bīng zhé jiàng",
  无可比拟: "wú kě bǐ nì",
  拐弯抹角: "guǎi wān mò jiǎo",
  像模像样: "xiàng mú xiàng yàng",
  供过于求: "gōng guò yú qiú",
  开花结果: "kāi huā jiē guǒ",
  仔仔细细: "zǐ zǐ xì xì",
  川藏公路: "chuān zàng gōng lù",
  河北梆子: "hé běi bāng zi",
  长年累月: "cháng nián lěi yuè",
  正儿八经: "zhèng er bā jīng",
  不识抬举: "bù shí tái ju",
  重振旗鼓: "chóng zhèn qí gǔ",
  气息奄奄: "qì xī yān yān",
  紧追不舍: "jǐn zhuī bù shě",
  服服帖帖: "fú fu tiē tiē",
  强词夺理: "qiǎng cí duó lǐ",
  噼里啪啦: "pī li pā lā",
  人才济济: "rén cái jǐ jǐ",
  发人深省: "fā rén shēn xǐng",
  不足为凭: "bù zú wéi píng",
  为富不仁: "wéi fù bù rén",
  连篇累牍: "lián piān lěi dú",
  呼天抢地: "hū tiān qiāng dì",
  落落大方: "luò luò dà fāng",
  自吹自擂: "zì chuī zì léi",
  乐善好施: "lè shàn hào shī",
  以攻为守: "yǐ gōng wéi shǒu",
  磨磨蹭蹭: "mó mó cèng cèng",
  削铁如泥: "xuē tiě rú ní",
  助纣为虐: "zhù zhòu wéi nüè",
  以退为进: "yǐ tuì wéi jìn",
  嘁嘁喳喳: "qī qī chā chā",
  枪林弹雨: "qiāng lín dàn yǔ",
  令人发指: "lìng rén fà zhǐ",
  转败为胜: "zhuǎn bài wéi shèng",
  转弯抹角: "zhuǎn wān mò jiǎo",
  在劫难逃: "zài jié nán táo",
  正当防卫: "zhèng dàng fáng wèi",
  不足为怪: "bù zú wéi guài",
  难兄难弟: "nàn xiōng nàn dì",
  咿咿呀呀: "yī yī yā yā",
  弹尽粮绝: "dàn jìn liáng jué",
  阿谀奉承: "ē yú fèng chéng",
  稀里哗啦: "xī li huā lā",
  返老还童: "fǎn lǎo huán tóng",
  好高骛远: "hào gāo wù yuǎn",
  鹿死谁手: "lù sǐ shéi shǒu",
  差强人意: "chā qiáng rén yì",
  大吹大擂: "dà chuī dà léi",
  成家立业: "chéng jiā lì yè",
  自怨自艾: "zì yuàn zì yì",
  负债累累: "fù zhai lěi lěi",
  古为今用: "gǔ wéi jīn yòng",
  入土为安: "rù tǔ wéi ān",
  下不为例: "xià bù wéi lì",
  一哄而上: "yì hōng ér shàng",
  没头苍蝇: "méi tóu cāng ying",
  天差地远: "tiān chā dì yuǎn",
  风卷残云: "fēng juǎn cán yún",
  多灾多难: "duō zāi duō nàn",
  乳臭未干: "rǔ xiù wèi gān",
  行家里手: "háng jiā lǐ shǒu",
  狼狈为奸: "láng bèi wéi jiān",
  处变不惊: "chǔ biàn bù jīng",
  一唱一和: "yí chàng yí hè",
  一念之差: "yí niàn zhī chā",
  金蝉脱壳: "jīn chán tuō qiào",
  滴滴答答: "dī dī dā dā",
  硕果累累: "shuò guǒ léi léi",
  好整以暇: "hào zhěng yǐ xiá",
  红得发紫: "hóng de fā zǐ",
  传为美谈: "chuán wéi měi tán",
  富商大贾: "fù shāng dà gǔ",
  四海为家: "sì hǎi wéi jiā",
  失而复得: "shī ér fù de",
  了若指掌: "liǎo ruò zhǐ zhǎng",
  大有可为: "dà yǒu kě wéi",
  出头露面: "chū tóu lù miàn",
  鼓鼓囊囊: "gǔ gu nāng nāng",
  窗明几净: "chuāng míng jī jìng",
  泰然处之: "tài rán chǔ zhī",
  怒发冲冠: "nù fà chōng guān",
  有机玻璃: "yǒu jī bō li",
  骨头架子: "gǔ tou jià zi",
  义薄云天: "yì bó yún tiān",
  一丁点儿: "yī dīng diǎn er",
  时来运转: "shí lái yùn zhuǎn",
  陈词滥调: "chén cí làn diào",
  化整为零: "huà zhěng wéi líng",
  火烧火燎: "huǒ shāo huǒ liǎo",
  干脆利索: "gàn cuì lì suǒ",
  吊儿郎当: "diào er láng dāng",
  广种薄收: "guǎng zhòng bó shōu",
  种瓜得瓜: "zhòng guā dé guā",
  种豆得豆: "zhòng dòu dé dòu",
  难舍难分: "nán shě nán fēn",
  歃血为盟: "shà xuè wéi méng",
  奋发有为: "fèn fā yǒu wéi",
  阴错阳差: "yīn cuò yáng chā",
  东躲西藏: "dōng duǒ xī cáng",
  烟熏火燎: "yān xūn huǒ liǎo",
  钻牛角尖: "zuān niú jiǎo jiān",
  乔装打扮: "qiáo zhuāng dǎ bàn",
  改弦更张: "gǎi xián gēng zhāng",
  河南梆子: "hé nán bāng zi",
  好吃懒做: "hào chī lǎn zuò",
  何乐不为: "hé lè bù wéi",
  大出风头: "dà chū fēng tóu",
  攻城掠地: "gōng chéng lüè dì",
  漂漂亮亮: "piào piào liang liang",
  折衷主义: "zhé zhōng zhǔ yì",
  大马哈鱼: "dà mǎ hǎ yú",
  绿树成荫: "lǜ shù chéng yīn",
  率先垂范: "shuài xiān chuí fàn",
  家长里短: "jiā cháng lǐ duǎn",
  宽大为怀: "kuān dà wéi huái",
  左膀右臂: "zuǒ bǎng yòu bì",
  一笑了之: "yí xiào liǎo zhī",
  天下为公: "tiān xià wéi gōng",
  还我河山: "huán wǒ hé shān",
  何足为奇: "hé zú wéi qí",
  好自为之: "hǎo zì wéi zhī",
  风姿绰约: "fēng zī chuò yuē",
  大雨滂沱: "dà yǔ pāng tuó",
  传为佳话: "chuán wéi jiā huà",
  吃里扒外: "chī lǐ pá wài",
  重操旧业: "chóng cāo jiù yè",
  小家子气: "xiǎo jiā zi qì",
  少不更事: "shào bù gēng shì",
  难分难舍: "nán fēn nán shě",
  添砖加瓦: "tiān zhuān jiā wǎ",
  是非分明: "shì fēi fēn míng",
  舍我其谁: "shě wǒ qí shuí",
  偏听偏信: "piān tīng piān xìn",
  量入为出: "liàng rù wéi chū",
  降龙伏虎: "xiáng lóng fú hǔ",
  钢化玻璃: "gāng huà bō li",
  正中下怀: "zhèng zhòng xià huái",
  以身许国: "yǐ shēn xǔ guó",
  一语中的: "yì yǔ zhòng dì",
  丧魂落魄: "sàng hún luò pò",
  三座大山: "sān zuò dà shān",
  济济一堂: "jǐ jǐ yì táng",
  好事之徒: "hào shì zhī tú",
  干净利索: "gàn jìng lì suǒ",
  出将入相: "chū jiàng rù xiàng",
  袅袅娜娜: "niǎo niǎo nuó nuó",
  狐狸尾巴: "hú li wěi ba",
  好逸恶劳: "hào yì wù láo",
  大而无当: "dà ér wú dàng",
  打马虎眼: "dǎ mǎ hu yǎn",
  板上钉钉: "bǎn shàng dìng dīng",
  吆五喝六: "yāo wǔ hè liù",
  虾兵蟹将: "xiā bīng xiè jiàng",
  水调歌头: "shuǐ diào gē tóu",
  数典忘祖: "shǔ diǎn wàng zǔ",
  人事不省: "rén shì bù xǐng",
  曲高和寡: "qǔ gāo hè guǎ",
  屡教不改: "lǚ jiào bù gǎi",
  互为因果: "hù wéi yīn guǒ",
  互为表里: "hù wéi biǎo lǐ",
  厚此薄彼: "hòu cǐ bó bǐ",
  过关斩将: "guò guān zhǎn jiàng",
  疙疙瘩瘩: "gē ge dā dā",
  大腹便便: "dà fù pián pián",
  走为上策: "zǒu wéi shàng cè",
  冤家对头: "yuān jia duì tóu",
  有隙可乘: "yǒu xì kě chèng",
  一鳞半爪: "yì lín bàn zhǎo",
  片言只语: "piàn yán zhǐ yǔ",
  开花结实: "kāi huā jié shí",
  经年累月: "jīng nián lěi yuè",
  含糊其词: "hán hú qí cí",
  寡廉鲜耻: "guǎ lián xiǎn chǐ",
  成年累月: "chéng nián lěi yuè",
  不徇私情: "bú xùn sī qíng",
  不当人子: "bù dāng rén zǐ",
  膀大腰圆: "bǎng dà yāo yuán",
  指腹为婚: "zhǐ fù wéi hūn",
  这么点儿: "zhè me diǎn er",
  意兴索然: "yì xīng suǒ rán",
  绣花枕头: "xiù huā zhěn tou",
  无的放矢: "wú dì fàng shǐ",
  望闻问切: "wàng wén wèn qiè",
  舍己为人: "shě jǐ wèi rén",
  穷年累月: "qióng nián lěi yuè",
  排难解纷: "pái nàn jiě fēn",
  处之泰然: "chǔ zhī tài rán",
  指鹿为马: "zhǐ lù wéi mǎ",
  危如累卵: "wēi rú lěi luǎn",
  天兵天将: "tiān bīng tiān jiàng",
  舍近求远: "shě jìn qiú yuǎn",
  南腔北调: "nán qiāng běi diào",
  苦中作乐: "kǔ zhōng zuò lè",
  厚积薄发: "hòu jī bó fā",
  臭味相投: "xiù wèi xiāng tóu",
  长幼有序: "zhǎng yòu yǒu xù",
  逼良为娼: "bī liáng wéi chāng",
  悲悲切切: "bēi bēi qiè qiē",
  败军之将: "bài jūn zhī jiàng",
  欺行霸市: "qī háng bà shì",
  削足适履: "xuē zú shì lǚ",
  先睹为快: "xiān dǔ wéi kuài",
  啼饥号寒: "tí jī háo hán",
  疏不间亲: "shū bú jiàn qīn",
  神差鬼使: "shén chāi guǐ shǐ",
  敲敲打打: "qiāo qiāo dǎ dǎ",
  平铺直叙: "píng pū zhí xù",
  没头没尾: "méi tóu mò wěi",
  寥寥可数: "liáo liáo kě shǔ",
  哼哈二将: "hēng hā èr jiàng",
  鹤发童颜: "hè fà tóng yán",
  各奔前程: "gè bèn qián chéng",
  弹无虚发: "dàn wú xū fā",
  大人先生: "dà rén xiān sheng",
  与民更始: "yǔ mín gēng shǐ",
  叶落归根: "yè luò huī gēn",
  树碑立传: "shù bēi lì zhuàn",
  是非得失: "shì fēi dé shī",
  实逼处此: "shí bī chǔ cǐ",
  塞翁失马: "sài wēng shī mǎ",
  日薄西山: "rì bó xī shān",
  切身体会: "qiè shēn tǐ huì",
  片言只字: "piàn yán zhǐ zì",
  跑马卖解: "pǎo mǎ mài xiè",
  宁折不弯: "nìng zhé bù wān",
  零零散散: "líng líng sǎn sǎn",
  量体裁衣: "liàng tǐ cái yī",
  连中三元: "lián zhòng sān yuán",
  礼崩乐坏: "lǐ bēng yuè huài",
  不为已甚: "bù wéi yǐ shèn",
  转悲为喜: "zhuǎn bēi wéi xǐ",
  以眼还眼: "yǐ yǎn huán yǎn",
  蔚为大观: "wèi wéi dà guān",
  未为不可: "wèi wéi bù kě",
  童颜鹤发: "tóng yán hè fà",
  朋比为奸: "péng bǐ wéi jiān",
  莫此为甚: "mò cǐ wéi shèn",
  夹枪带棒: "jiā qiāng dài bàng",
  富商巨贾: "fù shāng jù jiǎ",
  多劳多得: "duō láo duō de",
  淡然处之: "dàn rán chǔ zhī",
  箪食壶浆: "dān shí hú jiāng",
  创巨痛深: "chuāng jù tòng shēn",
  草长莺飞: "cǎo zhǎng yīng fēi",
  坐视不救: "zuò shī bú jiù",
  以己度人: "yǐ jǐ duó rén",
  随行就市: "suí háng jiù shì",
  文以载道: "wén yǐ zài dào",
  文不对题: "wén bú duì tí",
  铁板钉钉: "tiě bǎn dìng dīng",
  身体发肤: "shēn tǐ fà fū",
  缺吃少穿: "quē chī shǎo chuān",
  目无尊长: "mù wú zūn zhǎng",
  吉人天相: "jí rén tiān xiàng",
  毁家纾难: "huǐ jiā shū nàn",
  钢筋铁骨: "gāng jīn tiě gǔ",
  丢卒保车: "diū zú bǎo jū",
  丢三落四: "diū sān là sì",
  闭目塞听: "bì mù sè tīng",
  削尖脑袋: "xuē jiān nǎo dài",
  为非作恶: "wéi fēi zuò è",
  人才难得: "rén cái nán dé",
  情非得已: "qíng fēi dé yǐ",
  切中要害: "qiè zhòng yào hài",
  火急火燎: "huǒ jí huǒ liǎo",
  画地为牢: "huà dì wéi láo",
  好酒贪杯: "hào jiǔ tān bēi",
  长歌当哭: "cháng gē dàng kū",
  载沉载浮: "zài chén zài fú",
  遇难呈祥: "yù nàn chéng xiáng",
  榆木疙瘩: "yú mù gē da",
  以邻为壑: "yǐ lín wéi hè",
  洋为中用: "yáng wéi zhōng yòng",
  言为心声: "yán wéi xīn shēng",
  言必有中: "yán bì yǒu zhòng",
  图穷匕见: "tú qióng bǐ xiàn",
  滂沱大雨: "páng tuó dà yǔ",
  目不暇给: "mù bù xiá jǐ",
  量才录用: "liàng cái lù yòng",
  教学相长: "jiào xué xiāng zhǎng",
  悔不当初: "huǐ bù dāng chū",
  呼幺喝六: "hū yāo hè liù",
  不足为训: "bù zú wéi xùn",
  不拘形迹: "bù jū xíng jī",
  傍若无人: "páng ruò wú rén",
  八大山人: "bā tài shān rén",
  罪责难逃: "zuì zé nán táo",
  自我吹嘘: "zì wǒ chuī xū",
  转祸为福: "zhuǎn huò wéi fú",
  勇冠三军: "yǒng guàn sān jūn",
  易地而处: "yì dì ér chǔ",
  卸磨杀驴: "xiè mò shā lǘ",
  玩儿不转: "wán ér bú zhuàn",
  天道好还: "tiān dào hǎo huán",
  身单力薄: "shēn dān lì bó",
  撒豆成兵: "sǎ dòu chéng bīng",
  曲里拐弯: "qū li guǎi wān",
  片纸只字: "piàn zhǐ yán zì",
  宁缺毋滥: "nìng quē wú làn",
  没没无闻: "mò mò wú wén",
  量力而为: "liàng lì ér wéi",
  历历可数: "lì lì kě shǔ",
  口碑载道: "kǒu bēi zài dào",
  君子好逑: "jūn zǐ hǎo qiú",
  好为人师: "hào wéi rén shī",
  豪商巨贾: "háo shāng jù jiǎ",
  各有所好: "gè yǒu suǒ hào",
  度德量力: "duó dé liàng lì",
  指天为誓: "zhǐ tiān wéi shì",
  逸兴遄飞: "yì xìng chuán fēi",
  心宽体胖: "xīn kuān tǐ pán",
  为德不卒: "wéi dé bù zú",
  天下为家: "tiān xià wéi jiā",
  视为畏途: "shì wéi wèi tú",
  三灾八难: "sān zāi bā nàn",
  沐猴而冠: "mù hóu ér guàn",
  哩哩啦啦: "lī li lā lā",
  见缝就钻: "jiàn fèng jiù zuān",
  夹层玻璃: "jiā céng bō li",
  急公好义: "jí gōng hào yì",
  积年累月: "jī nián lěi yuè",
  划地为牢: "huá dì wéi láo",
  更名改姓: "gēng míng gǎi xìng",
  奉为圭臬: "fèng wéi guī niè",
  多难兴邦: "duō nàn xīng bāng",
  不破不立: "bú pò bú lì",
  坐地自划: "zuò dì zì huá",
  坐不重席: "zuò bù chóng xí",
  坐不窥堂: "zuò bù kuī táng",
  作嫁衣裳: "zuò jià yī shang",
  左枝右梧: "zuǒ zhī yòu wú",
  左宜右有: "zuǒ yí yòu yǒu",
  钻头觅缝: "zuān tóu mì fèng",
  钻天打洞: "zuān tiān dǎ dòng",
  钻皮出羽: "zuān pí chū yǔ",
  钻火得冰: "zuān huǒ dé bīng",
  钻洞觅缝: "zuàn dòng mì féng",
  钻冰求火: "zuān bīng qiú huǒ",
  纵曲枉直: "zòng qǔ wǎng zhí",
  子为父隐: "zǐ wéi fù yǐn",
  擢发难数: "zhuó fà nán shǔ",
  着人先鞭: "zhuó rén xiān biān",
  斫雕为朴: "zhuó diāo wéi pǔ",
  锥处囊中: "zhuī chǔ náng zhōng",
  椎心饮泣: "chuí xīn yǐn qì",
  椎心泣血: "chuí xīn qì xuè",
  椎牛飨士: "chuí niú xiǎng shì",
  椎牛歃血: "chuí niú shà xuè",
  椎牛发冢: "chuí niú fà zhǒng",
  椎埋屠狗: "chuí mái tú gǒu",
  椎埋狗窃: "chuí mái gǒu qiè",
  壮发冲冠: "zhuàng fā chōng guàn",
  庄严宝相: "zhuāng yán bǎo xiàng",
  转愁为喜: "zhuǎn chóu wéi xǐ",
  转嗔为喜: "zhuǎn chēn wéi xǐ",
  拽巷啰街: "zhuài xiàng luó jiē",
  拽耙扶犁: "zhuāi pá fú lí",
  拽布拖麻: "zhuài bù tuō má",
  箸长碗短: "zhù cháng wǎn duǎn",
  铸剑为犁: "zhù jiàn wéi lí",
  杼柚其空: "zhù zhóu qí kōng",
  杼柚空虚: "zhù zhóu kōng xū",
  助天为虐: "zhù tiān wéi nüè",
  属垣有耳: "zhǔ yuán yǒu ěr",
  属毛离里: "zhǔ máo lí lǐ",
  属辞比事: "zhǔ cí bǐ shì",
  逐物不还: "zhú wù bù huán",
  铢量寸度: "zhū liáng cùn duó",
  铢两悉称: "zhū liǎng xī chèn",
  侏儒观戏: "zhū rú guān xì",
  朱轓皁盖: "zhū fān zào gài",
  昼度夜思: "zhòu duó yè sī",
  诪张为幻: "zhōu zhāng wéi huàn",
  周郎顾曲: "zhōu láng gù qǔ",
  重明继焰: "chóng míng jì yàn",
  众啄同音: "zhòng zhuó tóng yīn",
  众毛攒裘: "zhòng máo cuán qiú",
  众好众恶: "zhòng hào zhòng wù",
  擿埴索涂: "zhāi zhí suǒ tú",
  稚齿婑媠: "zhì chǐ wǒ tuó",
  至当不易: "zhì dàng bú yì",
  指皂为白: "zhǐ zào wéi bái",
  指雁为羹: "zhǐ yàn wéi gēng",
  指树为姓: "zhǐ shù wéi xìng",
  指山说磨: "zhǐ shān shuō mò",
  止戈为武: "zhǐ gē wéi wǔ",
  枝干相持: "zhī gàn xiāng chí",
  枝大于本: "zh dà yú běn",
  支吾其词: "zhī wú qí cí",
  正身率下: "zhèng shēn shuài xià",
  正冠李下: "zhèng guàn lǐ xià",
  整冠纳履: "zhěng guān nà lǚ",
  整躬率物: "zhěng gōng shuài wù",
  整顿干坤: "zhěng dùn gàn kūn",
  针头削铁: "zhēn tóu xuē tiě",
  贞松劲柏: "zhēn sōng jìng bǎi",
  赭衣塞路: "zhě yī sè lù",
  折箭为誓: "shé jiàn wéi shì",
  折而族之: "zhé ér zú zhī",
  昭德塞违: "zhāo dé sè wéi",
  章句小儒: "zhāng jù xiǎo rú",
  湛恩汪濊: "zhàn ēn wāng huì",
  占风望气: "zhān fēng wàng qì",
  斩将搴旗: "zhǎn jiàng qiān qí",
  詹言曲说: "zhān yán qǔ shuō",
  曾母投杼: "zēng mǔ tóu zhù",
  曾参杀人: "zēng shēn shā rén",
  造谣中伤: "zào yáo zhòng shāng",
  早占勿药: "zǎo zhān wù yào",
  凿龟数策: "záo guī shǔ cè",
  攒三聚五: "cuán sān jù wǔ",
  攒眉蹙额: "cuán mei cù é",
  攒零合整: "cuán líng hé zhěng",
  攒锋聚镝: "cuán fēng jù dí",
  载笑载言: "zài xiào zài yán",
  载酒问字: "zài jiǔ wèn zì",
  殒身不恤: "yǔn shēn bú xù",
  云舒霞卷: "yún shū xiá juǎn",
  月中折桂: "yuè zhōng shé guì",
  月落参横: "yuè luò shēn héng",
  鬻驽窃价: "yù nú qiè jià",
  鬻鸡为凤: "yù jī wéi fèng",
  遇难成祥: "yù nàn chéng xiáng",
  郁郁累累: "yù yù lěi lěi",
  玉卮无当: "yù zhī wú dàng",
  语笑喧阗: "yǔ xiào xuān tián",
  与世沉浮: "yǔ shì chén fú",
  与时消息: "yǔ shí xiāo xi",
  逾墙钻隙: "yú qiáng zuān xì",
  渔夺侵牟: "yú duó qīn móu",
  杅穿皮蠹: "yú chuān pí dù",
  余勇可贾: "yú yǒng kě gǔ",
  予智予雄: "yú zhì yú xióng",
  予取予求: "yú qǔ yú qiú",
  于家为国: "yú jiā wéi guó",
  有借无还: "yǒu jiè wú huán",
  有加无已: "yǒu jiā wú yǐ",
  有国难投: "yǒu guó nán tóu",
  游必有方: "yóu bì yǒu fāng",
  油干灯尽: "yóu gàn dēng jìn",
  尤云殢雨: "yóu yún tì yǔ",
  庸中皦皦: "yōng zhōng jiǎo jiǎo",
  郢书燕说: "yǐng shū yān shuō",
  营蝇斐锦: "yíng yíng fēi jǐn",
  鹰心雁爪: "yīng xīn yàn zhǎo",
  莺吟燕儛: "yīng yín yàn wǔ",
  应天顺时: "yīng tiān shùn shí",
  印累绶若: "yìn léi shòu ruò",
  隐占身体: "yǐn zhàn shēn tǐ",
  饮犊上流: "yìn dú shàng liú",
  引绳切墨: "yǐn shéng qiē mò",
  龈齿弹舌: "yín chǐ dàn shé",
  淫词艳曲: "yín cí yàn qǔ",
  因缘为市: "yīn yuán wéi shì",
  因树为屋: "yīn shù wéi wū",
  溢美溢恶: "yì měi yì wù",
  抑塞磊落: "yì sè lěi luò",
  倚闾望切: "yǐ lǘ wàng qiē",
  以意为之: "yǐ yì wéi zhī",
  以言为讳: "yǐ yán wéi huì",
  以疏间亲: "yǐ shū jiàn qīn",
  以水济水: "yǐ shuǐ jǐ shuǐ",
  以书为御: "yǐ shū wéi yù",
  以守为攻: "yǐ shǒu wéi gōng",
  以升量石: "yǐ shēng liáng dàn",
  以慎为键: "yǐ shèn wéi jiàn",
  以筌为鱼: "yǐ quán wéi yú",
  以利累形: "yǐ lì lěi xíng",
  以毁为罚: "yǐ huǐ wéi fá",
  以黑为白: "yǐ hēi wéi bái",
  以规为瑱: "yǐ guī wéi tiàn",
  以古为鉴: "yǐ gǔ wéi jiàn",
  以宫笑角: "yǐ gōng xiào jué",
  以法为教: "yǐ fǎ wéi jiào",
  以大恶细: "yǐ dà wù xì",
  遗世忘累: "yí shì wàng lěi",
  遗寝载怀: "yí qǐn zài huái",
  移的就箭: "yí dì jiù jiàn",
  依头缕当: "yī tóu lǚ dàng",
  衣租食税: "yì zū shí shuì",
  衣轻乘肥: "yì qīng chéng féi",
  衣裳之会: "yī shang zhī huì",
  衣单食薄: "yī dān shí bó",
  一还一报: "yì huán yí bào",
  叶公好龙: "yè gōng hào lóng",
  野调无腔: "yě diào wú qiāng",
  瑶池女使: "yáo chí nǚ shǐ",
  幺麽小丑: "yāo mó xiǎo chǒu",
  养精畜锐: "yǎng jīng xù ruì",
  卬首信眉: "áng shǒu shēn méi",
  洋洋纚纚: "yáng yáng sǎ sǎ",
  羊羔美酒: "yáng gāo měi jiǔ",
  羊肠九曲: "yáng cháng jiǔ qǔ",
  扬风扢雅: "yáng fēng jié yǎ",
  燕昭市骏: "yān zhāo shì jùn",
  燕昭好马: "yān zhāo hǎo mǎ",
  燕石妄珍: "yān shí wàng zhēn",
  燕骏千金: "yān jùn qiān jīn",
  燕金募秀: "yān jīn mù xiù",
  燕驾越毂: "yān jià yuè gǔ",
  燕歌赵舞: "yān gē zhào wǔ",
  燕岱之石: "yān dài zhī shí",
  燕处危巢: "yàn chǔ wēi cháo",
  掞藻飞声: "shàn zǎo fēi shēng",
  偃革为轩: "yǎn gé wéi xuān",
  妍蚩好恶: "yán chī hǎo è",
  压良为贱: "yā liáng wéi jiàn",
  搀行夺市: "chān háng duó shì",
  泣数行下: "qì shù háng xià",
  当行出色: "dāng háng chū sè",
  秀出班行: "xiù chū bān háng",
  儿女成行: "ér nǚ chéng háng",
  大行大市: "dà háng dà shì",
  寻行数墨: "xún háng shǔ mò",
  埙篪相和: "xūn chí xiāng hè",
  血债累累: "xuè zhài lěi lěi",
  炫玉贾石: "xuàn yù gǔ shí",
  炫石为玉: "xuàn shí wéi yù",
  悬石程书: "xuán dàn chéng shū",
  悬狟素飡: "xuán huán sù cān",
  悬龟系鱼: "xuán guī xì yú",
  揎拳捋袖: "xuān quán luō xiù",
  轩鹤冠猴: "xuān hè guàn hóu",
  畜妻养子: "xù qī yǎng zǐ",
  羞人答答: "xiū rén dā dā",
  修鳞养爪: "xiū lín yǎng zhǎo",
  熊据虎跱: "xióng jù hǔ zhì",
  兄死弟及: "xiōng sǐ dì jí",
  腥闻在上: "xīng wén zài shàng",
  兴文匽武: "xīng wén yǎn wǔ",
  兴观群怨: "xìng guān qún yuàn",
  兴高彩烈: "xìng gāo cǎi liè",
  心手相应: "xīn shǒu xiāng yìng",
  心口相应: "xīn kǒu xiāng yīng",
  挟势弄权: "xié shì nòng quán",
  胁肩累足: "xié jiān lěi zú",
  校短量长: "jiào duǎn liáng cháng",
  小眼薄皮: "xiǎo yǎn bó pí",
  小廉曲谨: "xiǎo lián qǔ jǐn",
  硝云弹雨: "xiāo yún dàn yǔ",
  鸮鸣鼠暴: "xiāo míng shǔ bào",
  削株掘根: "xuē zhū jué gēn",
  削铁无声: "xuē tiě wú shēng",
  削职为民: "xuē zhí wéi mín",
  削木为吏: "xuē mù wéi lì",
  想望风褱: "xiǎng wàng fēng huái",
  香培玉琢: "xiang pei yu zhuó",
  相鼠有皮: "xiàng shǔ yǒu pí",
  相时而动: "xiàng shí ér dòng",
  相切相磋: "xiāng qiē xiāng cuō",
  相女配夫: "xiàng nǚ pèi fū",
  相门有相: "xiàng mén yǒu xiàng",
  挦章撦句: "xián zhāng chě jù",
  先我着鞭: "xiān wǒ zhuó biān",
  习焉不察: "xí yān bù chá",
  歙漆阿胶: "shè qī ē jiāo",
  晰毛辨发: "xī máo biàn fà",
  悉索薄赋: "xī suǒ bó fù",
  雾鳞云爪: "wù lín yún zhǎo",
  物稀为贵: "wù xī wéi guì",
  碔砆混玉: "wǔ fū hùn yù",
  武断专横: "wǔ duàn zhuān héng",
  五石六鹢: "wǔ shí liù yì",
  五色相宣: "wǔ sè xiāng xuān",
  五侯七贵: "wǔ hóu qī guì",
  五侯蜡烛: "wǔ hòu là zhú",
  五羖大夫: "wǔ gǔ dà fū",
  吾自有处: "wú zì yǒu chǔ",
  无下箸处: "wú xià zhù chǔ",
  无伤无臭: "wú shāng wú xiù",
  无能为役: "wú néng wéi yì",
  无寇暴死: "wú kòu bào sǐ",
  无孔不钻: "wú kǒng bú zuàn",
  无间可乘: "wú jiān kě chéng",
  无间冬夏: "wú jiān dōng xià",
  无恶不为: "wú è bù wéi",
  无动为大: "wú dòng wéi dà",
  诬良为盗: "wū liáng wéi dào",
  握粟出卜: "wò sù chū bo",
  握拳透爪: "wò quán tòu zhǎo",
  文武差事: "wén wǔ chāi shì",
  委委佗佗: "wēi wēi tuó tuó",
  惟日为岁: "wéi rì wéi suì",
  帷薄不修: "wéi bó bù xiū",
  为善最乐: "wéi shàn zuì lè",
  为山止篑: "wéi shān zhǐ kuì",
  为仁不富: "wéi rén bú fù",
  为裘为箕: "wéi qiú wéi jī",
  为民父母: "wéi mín fù mǔ",
  为虺弗摧: "wéi huǐ fú cuī",
  为好成歉: "wéi hǎo chéng qiàn",
  为鬼为蜮: "wéi guǐ wéi yù",
  望风响应: "wàng fēng xiǎng yīng",
  望尘僄声: "wàng chén piào shēng",
  枉曲直凑: "wǎng qǔ zhí còu",
  往渚还汀: "wǎng zhǔ huán tīng",
  王贡弹冠: "wáng gòng dàn guàn",
  亡国大夫: "wáng guó dà fū",
  万贯家私: "wàn guàn jiā sī",
  晚食当肉: "wǎn shí dàng ròu",
  晚节不保: "wǎn jié bù bǎo",
  玩岁愒时: "wán suì kài shí",
  蛙蟆胜负: "wā má shèng fù",
  吞言咽理: "tūn yán yàn lǐ",
  颓垣断堑: "tuí yuán duàn qiàn",
  推干就湿: "tuī gàn jiù shī",
  剸繁决剧: "tuán fán jué jù",
  团头聚面: "tuán tóu jù miàn",
  兔丝燕麦: "tù sī yàn mài",
  兔头麞脑: "tù tóu zhāng nǎo",
  兔葵燕麦: "tù kuí yàn mài",
  吐哺握发: "tǔ bǔ wò fà",
  投传而去: "tóu zhuàn ér qù",
  头没杯案: "tóu mò bēi àn",
  头昏脑闷: "tóu hūn nǎo mèn",
  头会箕敛: "tóu kuài jī liǎn",
  头出头没: "tóu chū tóu mò",
  痛自创艾: "tòng zì chuāng yì",
  同恶相助: "tóng wù xiāng zhù",
  同恶相恤: "tóng wù xiāng xù",
  痌瘝在抱: "tōng guān zài bào",
  通文调武: "tōng wén diào wǔ",
  停留长智: "tíng liú zhǎng zhì",
  铁树开华: "tiě shù kāi huā",
  条贯部分: "tiáo guàn bù fēn",
  挑牙料唇: "tiǎo yá liào chún",
  挑么挑六: "tiāo yāo tiāo liù",
  挑唇料嘴: "tiǎo chún liào zuǐ",
  恬不为意: "tián bù wéi yì",
  恬不为怪: "tián bù wéi guài",
  天下为笼: "tiān xià wéi lóng",
  天台路迷: "tiān tái lù mí",
  天年不遂: "tiān nián bú suì",
  天宝当年: "tian bao dang nian",
  探囊胠箧: "tàn náng qū qiè",
  谭言微中: "tán yán wēi zhòng",
  谈言微中: "tán yán wēi zhòng",
  狧穅及米: "shì kāng jí mǐ",
  随物应机: "suí wù yīng jī",
  搜岩采干: "sōu yán cǎi gàn",
  薮中荆曲: "sǒu zhōng jīng qǔ",
  宋斤鲁削: "sòng jīn lǔ xuē",
  松筠之节: "sōng yún zhī jié",
  四亭八当: "sì tíng bā dàng",
  四马攒蹄: "sì mǎ cuán tí",
  四不拗六: "sì bú niù liù",
  思所逐之: "sī suǒ zhú zhī",
  丝恩发怨: "sī ēn fà yuàn",
  硕望宿德: "shuò wàng xiǔ dé",
  铄古切今: "shuò gǔ qiē jīn",
  顺风而呼: "shùn fēng ér hū",
  顺风吹火: "shùn fēng chuī huǒ",
  水中著盐: "shuǐ zhōng zhuó yán",
  双柑斗酒: "shuāng gān dǒu jiǔ",
  数米而炊: "shǔ mǐ ér chuī",
  数米量柴: "shǔ mǐ liáng chái",
  数理逻辑: "shù lǐ luó ji",
  数黑论黄: "shǔ hēi lùn huáng",
  数白论黄: "shǔ bái lùn huáng",
  束缊还妇: "shù yūn huán fù",
  束蒲为脯: "shù pú wéi pú",
  束椽为柱: "shù chuán wéi zhù",
  书缺有间: "shū quē yǒu jiàn",
  手足重茧: "shǒu zú chóng jiǎn",
  手足异处: "shǒu zú yì chǔ",
  手脚干净: "shǒu jiǎo gàn jìng",
  手不应心: "shǒu bù yīng xīn",
  螫手解腕: "shì shǒu jiě wàn",
  释知遗形: "shì zhī yí xíng",
  适时应务: "shì shí yīng wù",
  适情率意: "shì qíng shuài yì",
  适当其冲: "shì dāng qí chōng",
  视为知己: "shì wéi zhī jǐ",
  使羊将狼: "shǐ yáng jiàng láng",
  食为民天: "shí wéi mín tiān",
  拾掇无遗: "shí duō wú yí",
  实与有力: "shí yù yǒu lì",
  石英玻璃: "shí yīng bō li",
  石室金匮: "shí shì jīn guì",
  什袭珍藏: "shí xí zhēn cáng",
  什伍东西: "shí wǔ dōng xī",
  什围伍攻: "shí wéi wǔ gōng",
  十魔九难: "shí mó jiǔ nàn",
  诗书发冢: "shī shū fà zhǒng",
  虱处裈中: "shī chǔ kūn zhōng",
  师直为壮: "shī zhí wéi zhuàng",
  尸居龙见: "shī jū lóng xiàn",
  圣经贤传: "shèng jīng xián zhuàn",
  圣君贤相: "shèng jūn xián xiàng",
  生拖死拽: "shēng tuō sǐ zhuài",
  审曲面埶: "shěn qū miàn shì",
  审己度人: "shěn jǐ duó rén",
  神武挂冠: "shén wǔ guà guàn",
  神龙失埶: "shén lóng shī shì",
  深文曲折: "shēn wén qǔ shé",
  深厉浅揭: "shēn lì qiǎn qì",
  深谷为陵: "shēn gǔ wéi líng",
  深恶痛疾: "shēn wù tòng jí",
  深仇宿怨: "shēn chóu xiǔ yuàn",
  舍己为公: "shě jǐ wèi gōng",
  舍短取长: "shě duǎn qǔ cháng",
  舍策追羊: "shě cè zhuī yáng",
  蛇蝎为心: "shé xiē wéi xīn",
  少成若性: "shào chéng ruò xìng",
  上当学乖: "shàng dàng xué guāi",
  赏不当功: "shǎng bù dāng gōng",
  善自为谋: "shàn zì wéi móu",
  善为说辞: "shàn wéi shuō cí",
  善善恶恶: "shàn shàn wù è",
  善财难舍: "shàn cái nán shě",
  苫眼铺眉: "shān yǎn pū méi",
  讪牙闲嗑: "shàn yá xián kē",
  山阴乘兴: "shān yīn chéng xīng",
  山殽野湋: "shān yáo yě wéi",
  山溜穿石: "shān liù chuān shí",
  山节藻棁: "shān jié zǎo zhuō",
  沙鸥翔集: "sha ou xiang ji",
  杀鸡为黍: "shā jī wéi shǔ",
  色厉胆薄: "sè lì dǎn bó",
  桑荫未移: "sāng yīn wèi yí",
  桑荫不徙: "sāng yīn bù xǐ",
  桑土绸缪: "sāng tǔ chóu miù",
  桑户棬枢: "sāng hù juàn shū",
  三战三北: "sān zhàn sān běi",
  三瓦两舍: "sān wǎ liǎng shě",
  三人为众: "sān rén wèi zhòng",
  三差两错: "sān chā liǎng cuò",
  塞井焚舍: "sāi jǐng fén shě",
  洒心更始: "sǎ xīn gèng shǐ",
  洒扫应对: "sǎ sǎo yìng duì",
  软红香土: "ruǎn hóng xiāng tǔ",
  入吾彀中: "rù wú gòu zhōng",
  入铁主簿: "rù tiě zhǔ bù",
  入理切情: "rù lǐ qiē qíng",
  汝成人耶: "rǔ chéng rén yé",
  如水投石: "rú shuǐ tóu shí",
  如切如磋: "rú qiē rú cuō",
  如登春台: "rú dēng chūn tái",
  肉薄骨并: "ròu bó gǔ bìng",
  柔情绰态: "róu qíng chuò tài",
  戎马劻勷: "róng mǎ kuāng ráng",
  日中为市: "rì zhōng wéi shì",
  日月参辰: "rì yuè shēn chén",
  日省月修: "rì xǐng yuè xiū",
  日削月割: "rì xuē yuè gē",
  日省月试: "rì xǐng yuè shì",
  任达不拘: "rèn dá bù jū",
  人言藉藉: "rén yán jí jí",
  人模狗样: "rén mú gǒu yàng",
  人莫予毒: "rén mò yú dú",
  热熬翻饼: "rè áo fān bǐng",
  权倾中外: "quán qīng zhōng wai",
  圈牢养物: "juàn láo yǎng wù",
  取予有节: "qǔ yǔ yǒu jié",
  诎要桡腘: "qū yāo ráo guó",
  曲终奏雅: "qǔ zhōng zòu yǎ",
  曲意迎合: "qǔ yì yíng hé",
  曲学阿世: "qǔ xué ā shì",
  曲眉丰颊: "qǔ méi fēng jiá",
  曲肱而枕: "qū gōng ér zhěn",
  穷形尽相: "qióng xíng jìn xiàng",
  情凄意切: "qíng qī yì qiè",
  情见势屈: "qíng xiàn shì qū",
  情见乎辞: "qíng xiàn hū cí",
  清都绛阙: "qīng dōu jiàng què",
  倾肠倒肚: "qīng cháng dào dǔ",
  青紫被体: "qīng zǐ pī tǐ",
  青林黑塞: "qīng lín hēi sài",
  螓首蛾眉: "qín shǒu é méi",
  琴瑟之好: "qín sè zhī hào",
  且住为佳: "qiě zhù wéi jiā",
  切树倒根: "qiē shù dǎo gēn",
  切理餍心: "qiē lǐ yàn xīn",
  切近的当: "qiē jìn de dāng",
  翘足引领: "qiáo zú yǐn lǐng",
  巧发奇中: "qiǎo fā qí zhòng",
  强嘴拗舌: "jiàng zuǐ niù shé",
  强直自遂: "qiáng zhí zì suí",
  强死强活: "qiǎng sǐ qiǎng huó",
  强食自爱: "qiǎng shí zì ài",
  强食靡角: "qiǎng shí mí jiǎo",
  强弓劲弩: "qiáng gōng jìng nǔ",
  强聒不舍: "qiǎng guō bù shě",
  强凫变鹤: "qiáng fú biàn hè",
  强而后可: "qiǎng ér hòu kě",
  强得易贫: "qiǎng dé yì pín",
  遣兴陶情: "qiǎn xìng táo qíng",
  牵羊担酒: "qiān yáng dān jiǔ",
  千了百当: "qiān liǎo bǎi dàng",
  泣下如雨: "qì xià rú yǔ",
  起偃为竖: "qǐ yǎn wéi shù",
  岂弟君子: "kǎi tì jūn zǐ",
  綦溪利跂: "qí xī lì qí",
  棋输先著: "qí shū xiān zhuó",
  齐王舍牛: "qí wáng shě niú",
  欺天诳地: "qī tiān kuáng dì",
  普天率土: "pǔ tiān shuài tǔ",
  铺胸纳地: "pū xiōng nà dì",
  铺锦列绣: "pū jǐn liè xiù",
  破家为国: "pò jiā wèi guó",
  破觚为圜: "pò gū wéi yuán",
  萍飘蓬转: "píng piāo péng zhuàn",
  帡天极地: "píng tiān jí dì",
  屏声息气: "bǐng shēng xī qì",
  凭几据杖: "píng jī jù zhàng",
  贫嘴薄舌: "pín zuǐ bó shé",
  片语只辞: "piàn yǔ zhī cí",
  披发文身: "pī fà wén shēn",
  烹龙炮凤: "pēng lóng páo fèng",
  炰鳖脍鲤: "fǒu biē kuài lǐ",
  旁指曲谕: "páng zhǐ qǔ yù",
  旁引曲证: "páng yǐn qǔ zhèng",
  旁通曲畅: "páng tōng qǔ chàng",
  庞眉皓发: "páng méi hào fà",
  攀花折柳: "pān huā zhé liǔ",
  攀蟾折桂: "pān chán shé guì",
  女大难留: "nǚ dà nán liú",
  弄玉吹箫: "nòng yù chuī xiāo",
  弄管调弦: "nòng guǎn tiáo xián",
  弄粉调朱: "nòng fěn diào zhū",
  浓抹淡妆: "nóng mò dàn zhuāng",
  捻土为香: "niǎn tǔ wéi xiāng",
  年谊世好: "nián yì shì hǎo",
  年华垂暮: "nián huá chuí mù",
  儗不于伦: "nǐ bù yú lún",
  泥而不滓: "ní ér bù zǐ",
  能者为师: "néng zhě wéi shī",
  能不称官: "néng bú chèn guān",
  挠直为曲: "náo zhí wéi qū",
  难进易退: "nán jìn yì tuì",
  难得糊涂: "nán dé hú tú",
  南蛮鴂舌: "nán mán jué shé",
  南贩北贾: "nán fàn běi gǔ",
  内修外攘: "nèi xiū wai rǎng",
  内柔外刚: "nèi róu wai gāng",
  内峻外和: "nèi jùn wai hé",
  牧猪奴戏: "mù zhū nú xì",
  目眢心忳: "mù yuān xīn tún",
  目挑心招: "mù tiǎo xīn zhāo",
  目量意营: "mù liàng yì yíng",
  木头木脑: "mù tóu mù nǎo",
  木干鸟栖: "mù gàn niǎo qī",
  侔色揣称: "móu sè chuǎi chèn",
  莫予毒也: "mò yú dú yě",
  抹粉施脂: "mò fěn shī zhī",
  磨砻镌切: "mó lóng juān qiē",
  磨棱刓角: "mó léng wán jiǎo",
  摸门不着: "mō mén bù zháo",
  摸不着边: "mō bù zhuó biān",
  命中注定: "mìng zhōng zhù dìng",
  鸣鹤之应: "míng hè zhī yìng",
  明效大验: "míng xiào dà yàn",
  名我固当: "míng wǒ gù dāng",
  邈处欿视: "miǎo chǔ kǎn shì",
  黾穴鸲巢: "měng xué qú cháo",
  绵里薄材: "mián lǐ bó cái",
  靡有孑遗: "mǐ yǒu jié yí",
  靡衣偷食: "mǐ yī tōu shí",
  迷恋骸骨: "mí liàn hái gǔ",
  扪参历井: "mén shēn lì jǐng",
  门单户薄: "mén dān hù bó",
  昧旦晨兴: "mèi dàn chén xīng",
  冒名接脚: "mò míng jiē jiǎo",
  毛遂堕井: "máo suí duò jǐng",
  毛发倒竖: "máo fā dǎo shù",
  卖文为生: "mài wén wéi shēng",
  卖李钻核: "mài lǐ zuān hé",
  买椟还珠: "mǎi dú huán zhū",
  埋三怨四: "mán sān yuàn sì",
  马入华山: "mǎ rù huá shān",
  落魄江湖: "luò pò jiāng hú",
  落落难合: "luò luò nán hé",
  落草为寇: "luò cǎo wéi kòu",
  罗织构陷: "luó zhī gòu xiàn",
  鸾凤和鸣: "luán fèng hè míng",
  率由旧章: "shuài yóu jiù zhāng",
  率土同庆: "shuài tǔ tóng qìng",
  率兽食人: "shuài shòu shí rén",
  率土归心: "shuài tǔ guī xīn",
  率马以骥: "shuài mǎ yǐ jì",
  率尔成章: "shuài ěr chéng zhāng",
  鲁斤燕削: "lǔ jīn yàn xuē",
  漏尽更阑: "lòu jìn gēng lán",
  笼鸟槛猿: "lóng niǎo jiàn yuán",
  笼鸟池鱼: "lóng niǎo chí yú",
  龙游曲沼: "long you qu zhao",
  龙血玄黄: "lóng xuè xuán huáng",
  龙雕凤咀: "lóng diāo fèng jǔ",
  六尺之讬: "liù chǐ zhī tuō",
  令原之戚: "líng yuán zhī qī",
  令人捧腹: "lìng rén pěng fù",
  陵劲淬砺: "líng jìng cuì lì",
  临敌易将: "lín dí yì jiàng",
  裂裳衣疮: "liè shang yī chuāng",
  裂冠毁冕: "liè guàn huǐ miǎn",
  了无惧色: "liǎo wú jù sè",
  了身达命: "liǎo shēn dá mìng",
  了然无闻: "liǎo rán wú wén",
  了不可见: "liǎo bù kě jiàn",
  了不长进: "liǎo bù zhǎng jìn",
  燎发摧枯: "liǎo fà cuī kū",
  审时度势: "shěn shí duó shì",
  量小力微: "liàng xiǎo lì wēi",
  相时度力: "xiāng shí duó lì",
  量枘制凿: "liàng ruì zhì záo",
  量如江海: "liàng rú jiāng hǎi",
  量金买赋: "liàng jīn mǎi fù",
  量己审分: "liàng jǐ shěn fēn",
  敛骨吹魂: "liǎn gǔ chuī hún",
  詈夷为跖: "lì yí wéi zhí",
  利令志惛: "lì lìng zhì hūn",
  李广不侯: "lǐ guǎng bú hòu",
  礼为情貌: "lǐ wéi qíng mào",
  礼让为国: "lǐ ràng wéi guó",
  犁生骍角: "lí shēng xīng jiǎo",
  离本徼末: "lí běn jiǎo mò",
  楞眉横眼: "léng méi hèng yǎn",
  擂天倒地: "léi tiān dǎo dì",
  累足成步: "lěi zú chéng bù",
  累瓦结绳: "lěi wǎ jié shéng",
  累土至山: "lěi tǔ zhì shān",
  累土聚沙: "lěi tǔ jù shā",
  累卵之危: "lěi luǎn zhī wēi",
  累累如珠: "lěi lěi rú zhū",
  累块积苏: "lěi kuài jī sū",
  乐山乐水: "lè shān lè shuǐ",
  潦原浸天: "lǎo yuán jìn tiān",
  老师宿儒: "lǎo shī xiǔ rú",
  牢什古子: "láo shí gǔ zi",
  琅嬛福地: "láng huán fú dì",
  揆情度理: "kuí qíng duó lǐ",
  旷日累时: "kuàng rì lěi shí",
  匡救弥缝: "kuāng jiù mí fèng",
  枯树生华: "kū shù shēng huā",
  口轻舌薄: "kǒu qīng shé bó",
  口角生风: "kǒu jiǎo shēng fēng",
  口角春风: "kǒu jiǎo chūn fēng",
  口角风情: "kǒu jiǎo fēng qíng",
  口干舌焦: "kǒu gān shé jiāo",
  口腹之累: "kǒu fù zhī lěi",
  空腹便便: "kōng fù pián pián",
  嗑牙料嘴: "kē yá liào zuǐ",
  刻木为鹄: "kè mù wéi hú",
  咳珠唾玉: "ké zhū tuò yù",
  咳唾成珠: "ké tuò chéng zhū",
  抗颜为师: "kàng yán wéi shī",
  开华结果: "kāi huā jié guǒ",
  峻阪盐车: "jùn bǎn yán chē",
  嚼铁咀金: "jiáo tiě jǔ jīn",
  嚼墨喷纸: "jué mò pēn zhǐ",
  倔头强脑: "juè tóu jiàng nǎo",
  倔头倔脑: "juè tóu juè nǎo",
  倦鸟知还: "juàn niǎo zhī huán",
  卷席而葬: "juǎn xí ér zàng",
  卷甲倍道: "juǎn jiǎ bèi dào",
  聚米为山: "jù mǐ wéi shān",
  举手相庆: "jǔ shǒu xiāng qìng",
  举世混浊: "jǔ shì hún zhuó",
  鞠为茂草: "jū wéi mào cǎo",
  拘神遣将: "jū shén qiǎn jiàng",
  居下讪上: "jū xià shàn shàng",
  久要不忘: "jiǔ yāo bú wàng",
  九转功成: "jiǔ zhuǎn gōng chéng",
  九蒸三熯: "jiǔ zhēng sān hàn",
  敬业乐群: "jìng yè lè qún",
  井底虾蟆: "jǐng dǐ xiā má",
  旌旗卷舒: "jīng qí juǎn shū",
  荆棘载途: "jīng jí zài tú",
  经纶济世: "jing lun ji shi",
  禁舍开塞: "jìn shě kāi sāi",
  祲威盛容: "jìn wēi shèng róng",
  进退消长: "jìn tuì xiāo cháng",
  进退应矩: "jìn tuì yīng jǔ",
  进退触籓: "jìn tuì chù fān",
  进退跋疐: "jìn tuì bá zhì",
  尽多尽少: "jǐn duō jǐn shǎo",
  锦囊还矢: "jǐn náng huán shǐ",
  矜己自饰: "jīn jǐ zì shì",
  矜功负气: "jīn gōng fù qì",
  津关险塞: "jīn guān xiǎn sài",
  金吾不禁: "jīn wú bú jìn",
  金翅擘海: "jīn chì bāi hǎi",
  解衣衣人: "jiě yī yī rén",
  解人难得: "jiě rén nán dé",
  解铃系铃: "jiě líng xì líng",
  解发佯狂: "jiě fà yáng kuáng",
  诘屈磝碻: "jié qū áo qiāo",
  教猱升木: "jiāo náo shēng mù",
  较瘦量肥: "jiào shòu liàng féi",
  角立杰出: "jiǎo lì jié chū",
  焦沙烂石: "jiāo shā làn shí",
  骄儿騃女: "jiāo ér sì nǚ",
  浇风薄俗: "jiāo fēng bó sú",
  降妖捉怪: "xiáng yāo zhuō guài",
  将取固予: "jiāng qǔ gù yǔ",
  将门有将: "jiàng mén yǒu jiàng",
  将夺固与: "jiāng duó gù yǔ",
  将伯之助: "qiāng bó zhī zhù",
  槛花笼鹤: "jiàn huā lóng hè",
  鉴影度形: "jiàn yǐng duó xíng",
  渐不可长: "jiàn bù kě zhǎng",
  见素抱朴: "xiàn sù bào pǔ",
  见弃于人: "jiàn qì yú rén",
  简丝数米: "jiǎn sī shǔ mǐ",
  俭不中礼: "jiǎn bú zhòng lǐ",
  间见层出: "jiàn xiàn céng chū",
  尖嘴薄舌: "jiān zuǐ bó shé",
  甲冠天下: "jiǎ guàn tiān xià",
  葭莩之亲: "jiā fú zhī qīn",
  家累千金: "jiā lèi qiān jīn",
  家给人足: "jiā jǐ rén zú",
  家道从容: "jiā dào cóng róng",
  夹袋人物: "jiā dài rén wù",
  霁风朗月: "jì fēng lǎng yuè",
  寄兴寓情: "jì xìng yù qíng",
  计深虑远: "jì shēn lǜ yuǎn",
  计功量罪: "jì gōng liàng zuì",
  掎裳连襼: "jǐ shang lián yì",
  虮虱相吊: "jǐ shī xiāng diào",
  疾不可为: "jí bù kě wéi",
  极深研几: "jí shēn yán jī",
  及宾有鱼: "jí bīn yǒu yú",
  激薄停浇: "jī bó tíng jiāo",
  积素累旧: "jī sù lěi jiù",
  积时累日: "jī shí lěi rì",
  积露为波: "jī lù wéi bō",
  积德累功: "jī dé lěi gōng",
  积谗糜骨: "jī chán méi gǔ",
  击排冒没: "jī pái mào mò",
  祸为福先: "huò wéi fú xiān",
  祸福相依: "huò fú xiāng yī",
  获隽公车: "huò jùn gōng chē",
  混应滥应: "hùn yīng làn yīng",
  毁舟为杕: "huǐ zhōu wéi duò",
  毁钟为铎: "huǐ zhōng wéi duó",
  毁冠裂裳: "huǐ guān liè cháng",
  晦盲否塞: "huì máng pǐ sè",
  回船转舵: "huí chuán zhuàn duò",
  潢池盗弄: "huáng chí dào nòng",
  黄冠草履: "huáng guàn cǎo lǚ",
  黄发儿齿: "huáng fà ér chǐ",
  黄发垂髫: "huáng fà chuí tiáo",
  还珠返璧: "huán zhū fǎn bì",
  还年驻色: "huán nián zhù sè",
  还年却老: "huán nián què lǎo",
  坏裳为裤: "huài shang wéi kù",
  画荻和丸: "huà dí huò wán",
  化枭为鸠: "huà xiāo wéi jiū",
  化腐为奇: "huà fǔ wéi qí",
  化鸱为凤: "huà chī wéi fèng",
  花不棱登: "huā bu lēng dēng",
  户限为穿: "hù xiàn wéi chuān",
  呼卢喝雉: "hū lú hè zhì",
  呼来喝去: "hū lái hè qù",
  呼不给吸: "hū bù jǐ xī",
  厚味腊毒: "hòu wèi xī dú",
  厚德载物: "hòu dé zài wù",
  鸿渐于干: "hóng jiàn yú gàn",
  洪炉燎发: "hóng lú liáo fà",
  红绳系足: "hóng shéng jì zú",
  红不棱登: "hóng bu lēng dēng",
  横抢硬夺: "hèng qiǎng yìng duó",
  横恩滥赏: "hèng ēn làn shǎng",
  恨海难填: "hèn hǎi nán tián",
  鹤发鸡皮: "hè fà jī pí",
  涸思干虑: "hé sī gān lǜ",
  河涸海干: "hé hé hǎi gān",
  和颜说色: "hé yán yuè sè",
  合从连衡: "hé zòng lián héng",
  浩浩汤汤: "hào hào shāng shāng",
  好勇斗狠: "hào yǒng dòu hěn",
  好问则裕: "hào wèn zé yù",
  好为事端: "hào wéi shì duān",
  好问决疑: "hào wèn jué yí",
  好生之德: "hào shēng zhī dé",
  好奇尚异: "hǎo qí shàng yì",
  好恶不同: "hǎo è bù tóng",
  好丹非素: "hào dān fēi sù",
  豪干暴取: "háo gàn bào qǔ",
  毫发不爽: "háo fà bù shuǎng",
  寒酸落魄: "hán suān luò pò",
  含英咀华: "hán yīng jǔ huá",
  含糊不明: "hán hú bù míng",
  过为已甚: "guò wéi yǐ shèn",
  桂折兰摧: "guì shé lán cuī",
  规旋矩折: "guī xuán jǔ shé",
  广文先生: "guǎng wén xiān sheng",
  广譬曲谕: "guǎng pì qǔ yù",
  广陵散绝: "guǎng líng sǎn jué",
  冠山戴粒: "guàn shān dài lì",
  冠屦倒施: "guàn jù dǎo shī",
  挂席为门: "guà xí wéi mén",
  寡见鲜闻: "guǎ jiàn xiǎn wén",
  瓜葛相连: "guā gé xiāng lián",
  鼓吻奋爪: "gǔ wěn fèn zhǎo",
  古调单弹: "gǔ diào dān tán",
  古调不弹: "gǔ diào bù tán",
  姑射神人: "gū yè shén rén",
  苟合取容: "gǒu hé qǔ róng",
  狗续侯冠: "gǒu xù hòu guàn",
  钩爪锯牙: "gōu zhǎo jù yá",
  共枝别干: "gòng zhī bié gàn",
  共为唇齿: "gòng wéi chún chǐ",
  拱手而降: "gǒng shǒu ér xiáng",
  拱肩缩背: "gǒng jiān suō bèi",
  功薄蝉翼: "gōng bó chán yì",
  弓调马服: "gōng diào mǎ fú",
  更姓改物: "gēng xìng gǎi wù",
  更仆难数: "gēng pú nán shǔ",
  更令明号: "gēng lìng míng hào",
  更待干罢: "gèng dài gàn bà",
  更唱迭和: "gēng chàng dié hé",
  更长梦短: "gēng cháng mèng duǎn",
  各色名样: "gè sè míng yàng",
  格格不纳: "gé gé bú nà",
  格格不吐: "gé gé bù tǔ",
  告朔饩羊: "gù shuò xì yáng",
  膏车秣马: "gào chē mò mǎ",
  高义薄云: "gāo yì bó yún",
  岗头泽底: "gāng tóu zé dǐ",
  敢为敢做: "gǎn wéi gǎn zuò",
  甘分随时: "gān fèn suí shí",
  甘处下流: "gān chǔ xià liú",
  干啼湿哭: "gàn tí shī kū",
  干名犯义: "gàn míng fàn yì",
  干将莫邪: "gān jiāng mò yé",
  干城之将: "gān chéng zhī jiàng",
  腹载五车: "fù zài wǔ chē",
  父债子还: "fù zhài zǐ huán",
  父为子隐: "fù wéi zǐ yǐn",
  辅世长民: "fǔ shì zhǎng mín",
  福为祸始: "fú wéi huò shǐ",
  符号逻辑: "fú hào luó jí",
  浮收勒折: "fú shōu lè shé",
  肤受之愬: "fū shòu zhī sù",
  否终则泰: "pǐ zhōng zé tài",
  佛头著粪: "fó tóu zhuó fèn",
  奉为楷模: "fèng wéi kǎi mó",
  凤靡鸾吪: "fèng mǐ luán é",
  封豨修蛇: "fēng xī xiū shé",
  风影敷衍: "fēng yǐng fū yǎn",
  丰屋蔀家: "fēng wū bù jiā",
  粪土不如: "fèn tǔ bù rú",
  分风劈流: "fēn fēng pǐ liú",
  沸沸汤汤: "fèi fèi shāng shāng",
  菲食薄衣: "fěi shí bó yī",
  飞将数奇: "fēi jiàng shù qí",
  放辟邪侈: "fàng pì xié chǐ",
  方领圆冠: "fāng lǐng yuán guàn",
  泛应曲当: "fàn yīng qǔ dāng",
  犯而不校: "fàn ér bú jiào",
  返本还源: "fǎn běn huán yuán",
  反劳为逸: "fǎn láo wéi yì",
  法轮常转: "fǎ lún cháng zhuàn",
  罚不当罪: "fá bù dāng zuì",
  发引千钧: "fà yǐn qiān jūn",
  发奸擿伏: "fā jiān tī fú",
  发短心长: "fà duǎn xīn cháng",
  二竖为虐: "èr shù wéi nüè",
  儿女心肠: "ér nǚ xīn cháng",
  儿女亲家: "ér nǚ qìng jiā",
  恩不放债: "ēn bú fàng zhai",
  遏恶扬善: "è wù yáng shàn",
  饿殍枕藉: "è piǎo zhěn jí",
  饿殍载道: "è piǎo zài dào",
  恶醉强酒: "wù zuì qiǎng jiǔ",
  恶意中伤: "è yì zhòng shāng",
  恶湿居下: "wù shī jū xià",
  恶居下流: "wù jū xià liú",
  恶不去善: "wù bú qù shàn",
  扼吭夺食: "è háng duó shí",
  扼襟控咽: "è jīn kòng yān",
  峨峨汤汤: "é é shāng shāng",
  屙金溺银: "ē jīn niào yín",
  朵颐大嚼: "duǒ yí dà jiáo",
  夺人所好: "duó rén suǒ hào",
  多言数穷: "duō yán shuò qióng",
  多文为富: "duō wén wéi fù",
  多端寡要: "duō duān guǎ yào",
  多财善贾: "duō cái shàn gǔ",
  遁世无闷: "dùn shì wú mèn",
  遁迹黄冠: "dùn jì huáng guàn",
  堆案盈几: "duī àn yíng jī",
  断还归宗: "duàn huán guī zōng",
  短见薄识: "duǎn jiàn bó shí",
  蠹居棊处: "dù jū qí chǔ",
  度己以绳: "duó jǐ yǐ shéng",
  杜默为诗: "dù mò wéi shī",
  杜鹃啼血: "dù juān tí xuè",
  笃近举远: "dǔ jìn jǔ yuǎn",
  独有千秋: "dú yǒu qiān qiū",
  读书得间: "dú shū dé jiàn",
  斗转参横: "dǒu zhuǎn shēn héng",
  兜肚连肠: "dōu dǔ lián cháng",
  洞见症结: "dòng jiàn zhèng jié",
  恫疑虚喝: "dòng yí xū hè",
  动中窾要: "dòng zhōng kuǎn yào",
  东鸣西应: "dōng míng xī yīng",
  东鳞西爪: "dōng lín xī zhǎo",
  东量西折: "dōng liàng xī shé",
  东家西舍: "dōng jiā xī shè",
  东方将白: "dong fang jiang bai",
  东扯西拽: "dōng chě xī zhuāi",
  鼎铛有耳: "dǐng chēng yǒu ěr",
  鼎铛玉石: "dǐng chēng yù shí",
  钉头磷磷: "dīng tóu lín lín",
  跌宕不羁: "diē dàng bù jī",
  跌弹斑鸠: "diē dàn bān jiū",
  雕心雁爪: "diāo xīn yàn zhǎo",
  颠倒衣裳: "diān dǎo yī cháng",
  德薄能鲜: "dé bó néng xiǎn",
  得马折足: "dé mǎ shé zú",
  蹈其覆辙: "dǎo qí fù zhé",
  捣虚撇抗: "dǎo xū piē kàng",
  倒载干戈: "dào zài gān gē",
  倒裳索领: "dào cháng suǒ lǐng",
  倒果为因: "dào guǒ wéi yīn",
  叨在知己: "tāo zài zhī jǐ",
  叨陪末座: "tāo péi mò zuò",
  党豺为虐: "dǎng chái wéi nüè",
  当轴处中: "dāng zhóu chǔ zhōng",
  当着不着: "dāng zhuó bù zhuó",
  当务始终: "dāng wù shǐ zhōng",
  淡汝浓抹: "dàn rǔ nóng mǒ",
  弹丸脱手: "tán wán tuō shǒu",
  弹铗无鱼: "dàn jiá wú yú",
  箪食瓢饮: "dān sì piáo yǐn",
  大璞不完: "tài pú bù wán",
  大明法度: "dà míng fǎ dù",
  大车以载: "dà chē yǐ zài",
  打闷葫芦: "dǎ mèn hú lu",
  沓来踵至: "tà lái zhǒng zhì",
  厝火燎原: "cuò huǒ liǎo yuán",
  撮科打哄: "cuō kē dǎ hòng",
  寸积铢累: "cùn jī zhū lěi",
  啛啛喳喳: "cuì cuì chā chā",
  摧折豪强: "cuī zhé háo qiáng",
  摧刚为柔: "cuī gāng wéi róu",
  从俗就简: "cóng sú jiù jiǎn",
  此发彼应: "cǐ fā bǐ yīng",
  此唱彼和: "cǐ chàng bǐ hè",
  慈悲为本: "cí bēi wéi běn",
  纯属骗局: "chún shǔ piàn jú",
  春笋怒发: "chūn sǔn nù fā",
  垂头搨翼: "chuí tóu tà yì",
  传为笑谈: "chuán wéi xiào tán",
  传风扇火: "chuán fēng shān huǒ",
  穿红着绿: "chuān hóng zhuó lǜ",
  触处机来: "chù chǔ jī lái",
  处尊居显: "chǔ zūn jū xiǎn",
  处堂燕雀: "chǔ táng yàn què",
  处实效功: "chǔ shí xiào gōng",
  处高临深: "chǔ gāo lín shēn",
  出入无间: "chū rù wú jiān",
  出门应辙: "chū mén yīng zhé",
  出处语默: "chū chǔ yǔ mò",
  出处殊途: "chū chǔ shū tú",
  出处进退: "chū chǔ jìn tuì",
  愁山闷海: "chóu shān mèn hǎi",
  冲冠眦裂: "chōng guàn zì liè",
  齿牙为祸: "chǐ yá wéi huò",
  尺二冤家: "chǐ èr yuān jia",
  尺短寸长: "chǐ duǎn cùn cháng",
  尺寸之功: "chǐ cùn zhī gōng",
  城北徐公: "chéng běi xú gōng",
  成败兴废: "chéng bài xīng fèi",
  趁水和泥: "chèn shuǐ huò ní",
  称雨道晴: "chēng yǔ dào qíng",
  称体载衣: "chēng tǐ zài yī",
  称体裁衣: "chèn tǐ cái yī",
  称家有无: "chèn jiā yǒu wú",
  称德度功: "chēng dé duó gōng",
  沉吟章句: "chén yín zhāng jù",
  沉吟不决: "chén yín bù jué",
  沉疴宿疾: "chén kē sù jí",
  扯纤拉烟: "chě qiàn lā yān",
  扯顺风旗: "chě shùn fēng qí",
  车载船装: "chē zǎi chuán zhuāng",
  朝升暮合: "zhāo shēng mù gě",
  朝攀暮折: "zhāo pān mù shé",
  超今冠古: "chāo jīn guàn gǔ",
  倡而不和: "chàng ér bú hè",
  畅所欲为: "chàng suǒ yù wéi",
  苌弘碧血: "cháng hóng bì xiě",
  长幼尊卑: "zhǎng yòu zūn bēi",
  长绳系日: "cháng shéng jì rì",
  长年三老: "zhǎng nián sān lǎo",
  长春不老: "cháng chūn bù lǎo",
  长傲饰非: "zhǎng ào shì fēi",
  昌亭旅食: "chāng tíng lǚ shí",
  谄上抑下: "chǎn shàng yi xià",
  禅絮沾泥: "chán xù zhān ní",
  差三错四: "chā sān cuò sì",
  层台累榭: "céng tái lěi xiè",
  层见迭出: "céng xiàn dié chū",
  藏踪蹑迹: "cáng zōng niè jì",
  苍蝇见血: "cāng yíng jiàn xiě",
  餐松啖柏: "cān sōng dàn bó",
  骖风驷霞: "cān fēng sì xiá",
  参伍错综: "cēn wǔ cuò zōng",
  参辰卯酉: "shēn chén mǎo yǒu",
  材优干济: "cái yōu gān jǐ",
  材薄质衰: "cái bó zhì shuāi",
  才大难用: "cái dà nán yòng",
  才薄智浅: "cái bó zhì qiǎn",
  不足为意: "bù zú wéi yì",
  不足为据: "bù zú wéi jù",
  不足为法: "bù zú wéi fǎ",
  不足齿数: "bù zú chǐ shǔ",
  不着疼热: "bù zhuó téng rè",
  不知薡蕫: "bù zhī dǐng dǒng",
  不越雷池: "bú yuè léi chí",
  不亦善夫: "bù yi shàn fū",
  不相为谋: "bù xiāng wéi móu",
  不贪为宝: "bù tān wéi bǎo",
  不了而了: "bù liǎo ér liǎo",
  不可揆度: "bù kě kuí duó",
  不遑启处: "bù huáng qǐ chǔ",
  不当不正: "bù dāng bú zhèng",
  不差什么: "bú chà shén me",
  不差累黍: "bù chā lěi shǔ",
  擘两分星: "bò liǎng fēn xīng",
  簸土扬沙: "bǒ tǔ yáng shā",
  薄物细故: "bó wù xì gù",
  薄寒中人: "bó hán zhòng rén",
  博文约礼: "bó wén yuē lǐ",
  播糠眯目: "bō kāng mí mù",
  剥皮抽筋: "bō pí chōu jīn",
  剥肤椎髓: "bō fū chuí suǐ",
  波属云委: "bō zhǔ yún wěi",
  波骇云属: "bō hài yún zhǔ",
  兵微将寡: "bīng wēi jiàng guǎ",
  兵强将勇: "bīng qiáng jiàng yǒng",
  兵多将广: "bīng duō jiàng guǎng",
  兵不由将: "bīng bù yóu jiàng",
  冰解的破: "bīng jiě dì pò",
  彬彬济济: "bīn bīn jǐ jǐ",
  摽梅之年: "biào méi zhī nián",
  表里为奸: "biǎo lǐ wéi jiān",
  飙发电举: "biāo fā diàn jǔ",
  变贪厉薄: "biàn tān lì bó",
  敝盖不弃: "bì gài bú qì",
  秕言谬说: "bǐ yán miù shuō",
  比物属事: "bǐ wù zhǔ shì",
  被山带河: "pī shān dài hé",
  被甲枕戈: "pī jiǎ zhěn gē",
  被甲据鞍: "pī jiǎ jù ān",
  被褐怀玉: "pī hè huái yù",
  被发缨冠: "pī fà yīng guàn",
  背曲腰躬: "bèi qǔ yāo gōng",
  北窗高卧: "běi chuāng gāo wò",
  北辰星拱: "běi chén xīng gǒng",
  北鄙之音: "běi bǐ zhī yīn",
  卑宫菲食: "bēi gōng fěi shí",
  暴衣露冠: "pù yī lù guàn",
  暴腮龙门: "pù sāi lóng mén",
  暴露文学: "bào lù wén xué",
  暴虎冯河: "bào hǔ píng hé",
  抱蔓摘瓜: "bào wàn zhāi guā",
  抱法处势: "bào fǎ chǔ shì",
  褒贬与夺: "bāo biǎn yǔ duó",
  帮闲钻懒: "bāng xián zuān lǎn",
  拜将封侯: "bài jiàng fēng hóu",
  百兽率舞: "bǎi shòu shuài wǔ",
  百孔千创: "bǎi kǒng qiān chuāng",
  白衣卿相: "bái yī qīng xiàng",
  白首为郎: "bái shǒu wéi láng",
  白首相知: "bái shǒu xiāng zhī",
  把玩无厌: "bǎ wán wú yàn",
  拔锅卷席: "bá guō juǎn xí",
  拔本塞源: "bá běn sè yuán",
  傲不可长: "ào bù kě zhǎng",
  熬更守夜: "áo gēng shǒu yè",
  安时处顺: "ān shí chǔ shùn",
  安身为乐: "ān shēn wéi lè",
  安老怀少: "ān lǎo huái shào",
  安步当车: "ān bù dàng chē",
  爱人好士: "ài rén hào shì",
  矮人观场: "ǎi rén guān chǎng",
  捱风缉缝: "ái fēng jī fèng",
  挨山塞海: "āi shān sè hǎi",
  阿家阿翁: "ā jiā ā wēng",
  阿党相为: "ē dǎng xiāng wéi",
  追亡逐北: "zhuī wáng zhú běi",
  竹篮打水: "zhú lán dá shuǐ",
  知疼着热: "zhī téng zháo rè",
  语不惊人: "yǔ bù jīng rén",
  于今为烈: "yú jīn wéi liè",
  一日三省: "yí rì sān xǐng",
  穴居野处: "xué jū yě chǔ",
  五脊六兽: "wǔ jǐ liù shòu",
  无声无臭: "wú shēng wú xiù",
  谓予不信: "wèi yú bú xìn",
  舍身为国: "shě shēn wéi guó",
  杀妻求将: "shā qī qiú jiàng",
  曲不离口: "qǔ bù lí kǒu",
  强作解人: "qiǎng zuò jiě rén",
  气冲斗牛: "qì chōng dǒu niú",
  临深履薄: "lín shēn lǚ bó",
  钧天广乐: "jūn tiān guǎng yuè",
  艰难竭蹶: "jiān nán jié jué",
  夹七夹八: "jiā qī jiā bā",
  混混噩噩: "hún hún è è",
  厚古薄今: "hòu gǔ bó jīn",
  鬼怕恶人: "guǐ pà è rén",
  伽马射线: "gā mǎ shè xiàn",
  佛头着粪: "fó tóu zhuó fèn",
  奉为至宝: "fèng wéi zhì bǎo",
  登坛拜将: "dēng tán bài jiàng",
  晨昏定省: "chén hūn dìng xǐng",
  察察为明: "chá chá wéi míng",
  博闻强识: "bó wén qiáng zhì",
  避难就易: "bì nán jiù yì",
  了无生机: 'liǎo wú shēng jī',
};